Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-09, with the labels that each got.

#319 Fix bugs with generating arguments
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kParameterExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kPropertyExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/ArgumentBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/KParameterExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/ArgumentBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
Labels: changes: patch, type: bug

#320 Directives on constructor args with no prefix
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kPropertyExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/DirectiveBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InputObjectBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InputPropertyBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/PropertyBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/DirectiveBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/InputPropertyBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/PropertyBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
Labels: changes: patch, type: bug

#316 Fix nested federation
  examples/federation/base-app/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  examples/federation/base-app/src/main/kotlin/com/expedia/graphql/sample/query/NestedQuery.kt
  graphql-kotlin-federation/src/main/kotlin/com/expedia/graphql/federation/execution/FederatedTypeRegistry.kt
  graphql-kotlin-federation/src/test/kotlin/com/expedia/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expedia/graphql/federation/execution/EntityQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expedia/graphql/federation/execution/ServiceQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/test/data/queries/simple/NestedQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/test/integration/NodeGraphTest.kt
Labels: changes: patch, type: bug

#324 Remove all other references to ExpediaDotCom
  .travis/update-version.sh
  LICENSE
  README.md
  examples/federation/base-app/pom.xml
  examples/federation/pom.xml
  examples/pom.xml
  examples/spring/pom.xml
  examples/spring/src/main/kotlin/com/expedia/graphql/sample/SubscriptionHandler.kt
  graphql-kotlin-federation/README.md
  graphql-kotlin-schema-generator/README.md
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/graphQLExtensions.kt
Labels: type: documentation

#328 Update documentation
  CONTRIBUTING.md
  README.md
Labels: type: documentation

#327 add more test coverage for federation
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/resolvers.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/exception/FederatedRequestFailureTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ResolversKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/AnyTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/EntityTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/FieldSetTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/ServiceTest.kt
Labels: type: tool update

#330 Create CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: type: documentation

#331 Increase code coverage
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ResolversKtTest.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinFieldDirectiveEnvironment.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinSchemaDirectiveEnvironment.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/KotlinFieldDirectiveEnvironmentTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/KotlinSchemaDirectiveEnvironmentTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilderTest.kt
Labels: type: tool update

#333 Update contributors to generic EG
  pom.xml
Labels: type: documentation

#335 Github action for PR check
  .github/workflows/maven.yml
Labels: type: tool update

#336 Update READMEs with new maven central link
  README.md
  graphql-kotlin-federation/README.md
  graphql-kotlin-schema-generator/README.md
Labels: type: documentation

#339 Create build.yml
  .github/workflows/build.yml
Labels: type: tool update

#341 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation

#343 Add usage in the main README
  CONTRIBUTING.md
  README.md
Labels: type: documentation

#344 Fixing typo
  CONTRIBUTING.md
Labels: type: documentation

#345 BREAKING CHANGE: Change GraphQLID to only use strings
  examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/query/ScalarQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidIdTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ArgumentBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilderTest.kt
Labels: changes: major, type: enhancement

#346 feature: abstract away creation of GraphQL context
  examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/context/MyGraphQLContextFactory.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/GraphQLContextFactory.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/QueryHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandler.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/FederationConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SubscriptionConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilterTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/QueryHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandlerIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
Labels: type: enhancement

#348 Update CONTRIBUTING.md with license header
  CONTRIBUTING.md
Labels: type: documentation

#351 Fix travis script to update versions
  .travis/update-version.sh
  examples/federation/base-app/pom.xml
  examples/federation/extend-app/pom.xml
  examples/federation/pom.xml
  examples/pom.xml
  examples/spring/pom.xml
  graphql-kotlin-federation/pom.xml
  graphql-kotlin-schema-generator/pom.xml
  graphql-kotlin-spring-server/pom.xml
  pom.xml
Labels: type: tool update

#352 Delete build.yml
  .github/workflows/build.yml
Labels: type: tool update

#354 Update update-version.sh
  .travis/update-version.sh
Labels: type: tool update

#355 docs: Query and Mutation should be marker interfaces
  graphql-kotlin-spring-server/README.md
Labels: type: documentation

#357 tool update: latest detekt and ktlint
  .editorconfig
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Service.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/ConflictingTypesException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/CouldNotCastArgumentException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/CouldNotCastGraphQLType.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/CouldNotGetNameOfKClassException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/CouldNotGetNameOfKParameterException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/GraphQLKotlinException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidIdTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidInputFieldTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidListTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidQueryTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidSchemaDirectiveWiringException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidSubscriptionTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/NestingNonNullTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/TypeNotSupportedException.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/CustomDataFetcherTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/NodeGraphTest.kt
  pom.xml
Labels: type: tool update

#368 fix non nullable nested object marked as nullable
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/NestingNonNullTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/TypeBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/graphQLExtensions.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilderTest.kt
Labels: changes: patch, type: bug

#371 Fix Apollo subscription message handling
  detekt.yml
  examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/subscriptions/SimpleSubscription.kt
  examples/spring/src/main/resources/application.yml
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/UknownSubscriptionOperationType.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/SubscriptionOperationMessage.kt
  graphql-kotlin-spring-server/src/main/resources/META-INF/spring-configuration-metadata.json
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
Labels: changes: patch, type: bug

#376 Increase code coverage
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/KotlinDirectiveWiringFactoryTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/KotlinDataFetcherExceptionHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLErrorTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilterTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponseKtTest.kt
  pom.xml
Labels: type: documentation

#378 Upgrade library versions and unit tests
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaValidator.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/extensions/GraphQLDirectiveContainerExtensions.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Any.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateFieldSelection.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateKeySetField.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateProvidesDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateRequiresDirective.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/AnyTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateDirectiveKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateFieldSelectionKtTest.kt
  graphql-kotlin-schema-generator/pom.xml
  graphql-kotlin-spring-server/pom.xml
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLErrorTest.kt
  pom.xml
Labels: changes: patch, type: dependency changes, type: refactor

#379 Run intellij code clean up on all source files
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidSchemaException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandler.kt
Labels: changes: patch, type: refactor

#374 Remove custom directives from Federated GraphQL schema _service{sdl}
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
Labels: changes: patch, type: bug

#386 spring-server: context web filter should only apply on graphql routes
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/ContextWebFilterTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/GraphQLContextFactoryIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilterTest.kt
Labels: changes: patch, type: bug

#392 spring-server: include path in SimpleKotlinGraphQLError error message
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLError.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLErrorTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/QueryHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandlerTest.kt
Labels: changes: patch

#394 Missing @Component in ReadMe example
  graphql-kotlin-spring-server/README.md
Labels: type: documentation

#395 [spring-server] enable support for specifying instrumentation order
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/instrumentation/InstrumentationIT.kt
Labels: changes: patch, type: enhancement

#400 [spring-server] SimplQueryHandler support for DataLoaderRegistry
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/QueryHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLRequest.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/model/GraphQLRequestTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponseKtTest.kt
Labels: changes: minor, type: enhancement

#401 Create docs site
  .github/CODE_OF_CONDUCT.md
  .gitignore
  CONTRIBUTING.md
  README.md
  docs/contributors/release-proc.md
  docs/doc-main.md
  docs/examples/examples.md
  docs/execution/async-models.md
  docs/execution/data-fetching-environment.md
  docs/execution/subscriptions.md
  docs/federated/directives.md
  docs/federated/federated-schemas.md
  docs/federated/type-resolution.md
  docs/getting-started.md
  docs/server/spring-config.md
  docs/server/spring.md
  docs/writing-schemas/annotations.md
  docs/writing-schemas/arguments.md
  docs/writing-schemas/basics.md
  docs/writing-schemas/directives.md
  docs/writing-schemas/enums.md
  docs/writing-schemas/fields.md
  docs/writing-schemas/generator-config.md
  docs/writing-schemas/interfaces.md
  docs/writing-schemas/lists.md
  docs/writing-schemas/nested-queries.md
  docs/writing-schemas/nullability.md
  docs/writing-schemas/scalars.md
  docs/writing-schemas/unions.md
  graphql-kotlin-federation/README.md
  graphql-kotlin-schema-generator/README.md
  graphql-kotlin-spring-server/README.md
  website/README.md
  website/core/Footer.js
  website/package-lock.json
  website/package.json
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/static/css/custom.css
  website/static/img/EG_Icon_White_on_Blue.png
  website/static/img/Expedia-Group-Logo_E-Stacked.png
  website/static/img/favicon.ico
  website/static/img/kotlin-logo.svg
  website/static/img/undraw_code_review_l1q9.svg
  website/static/img/undraw_code_typing_7jnv.svg
  website/static/img/undraw_monitor.svg
  website/static/img/undraw_web_developer_p3e5.svg
Labels: type: documentation

#402 Update siteconifg for docs site
  .gitignore
  docs/doc-main.md
  website/.nvmrc
  website/README.md
  website/package-lock.json
  website/package.json
  website/sidebars.json
  website/siteConfig.js
Labels: type: documentation

#403 [federation] skip validation of nested objects under construction
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateProvidesDirective.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorProvidesDirectiveTest.kt
Labels: changes: patch, type: bug

#404 Create publish docs action
  .github/workflows/publish-docs.yml
Labels: type: tool update

#406 Exclude docs from coverage reports/checks
  codecov.yml
Labels: type: tool update

#405 Remove landing page in favor of docs only
  docs/doc-main.md
  docs/examples.md
  docs/getting-started.md
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/static/index.html
Labels: type: documentation
