Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-07, with the labels that each got.

#247 Explicit support for deprecated directive in the schema
  example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  example/src/main/kotlin/com/expedia/graphql/sample/RoutesConfiguration.kt
  src/main/kotlin/com/expedia/graphql/directives/DeprecatedDirective.kt
  src/main/kotlin/com/expedia/graphql/directives/KotlinDirectiveWiringFactory.kt
  src/main/kotlin/com/expedia/graphql/extensions/GraphQLSchemaExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/state/SchemaGeneratorState.kt
  src/main/kotlin/com/expedia/graphql/generator/types/EnumBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/PropertyBuilder.kt
  src/test/kotlin/com/expedia/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/DirectiveBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/EnumBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/PropertyBuilderTest.kt
Labels: changes: minor, type: enhancement

#251 Revert throwing exception on missing directive wiring
  src/main/kotlin/com/expedia/graphql/directives/KotlinDirectiveWiringFactory.kt
  src/test/kotlin/com/expedia/graphql/directives/KotlinDirectiveWiringFactoryTest.kt
Labels: changes: minor

#261 Update travis config on 0.6.x branch for tag release
  .travis.yml
Labels: type: tool update

#262 Add back the example script step
  .travis.yml
Labels: type: tool update

#268 publish only the schema-generator module
  pom.xml
Labels: type: tool update

#271 upgrade maven wrapper version
  .mvn/wrapper/maven-wrapper.properties
Labels: type: tool update

#272 feat: allow renaming of properties and functions
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/annotations/GraphQLName.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kCallableExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kPropertyExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InputObjectBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/PropertyBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/AnnotationExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/KCallableExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/KPropertyExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt
Labels: changes: minor, type: enhancement

#273 fix: use maven release plugin in update-version.sh travis script
  .travis/update-version.sh
Labels: type: tool update

#279 Add debug logging to update-versions.sh
  .travis/update-version.sh
Labels: type: tool update

#282 Fix type resolvers for renamed polymorphic types and fix hooks signature
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InterfaceBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/UnionBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/PolymorphicTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
Labels: changes: major, type: enhancement

#285 fix some compile warnings
  graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/datafetchers/SpringDataFetcherFactory.kt
  graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/extension/CustomSchemaGeneratorHooks.kt
  graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/query/PolymorphicQuery.kt
  graphql-kotlin-spring-example/src/test/kotlin/com/expedia/graphql/sample/extension/CustomSchemaGeneratorHooksTest.kt
Labels: type: documentation
