Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-10, with the labels that each got.

#408 Update README documentation link
  README.md
Labels: type: documentation

#409 Update docs link in other READMEs
  graphql-kotlin-federation/README.md
  graphql-kotlin-schema-generator/README.md
  graphql-kotlin-spring-server/README.md
Labels: type: documentation

#410 [spring-server] support for creating data loader registry per execution
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/DataLoaderRegistryFactory.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/QueryHandler.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
Labels: changes: minor, type: bug

#411 Update examples.md
  docs/examples.md
Labels: type: documentation

#396 Example of DataLoaders.
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/dataloaders/DataLoaderConfiguration.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/Organization.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/OrganizationQuery.kt
Labels: type: documentation

#417 [federation] fix: SDL should be generated for non-federated schemas
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
Labels: changes: patch, type: bug

#421 [spring-server] update to use Spring Boot RC1
  graphql-kotlin-spring-server/pom.xml
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/PlaygroundAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
  pom.xml
Labels: changes: minor, type: dependency changes

#425 [spring-server] fix: handle graphql request with charset coding
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
Labels: changes: patch, type: bug

#428 Fixed link to Gateway Readme
  examples/federation/README.md
Labels: type: documentation

#431 Move spring-boot version to single location
  examples/federation/base-app/pom.xml
  examples/federation/extend-app/pom.xml
  examples/federation/pom.xml
  examples/pom.xml
  examples/spring/README.md
  examples/spring/pom.xml
  graphql-kotlin-federation/pom.xml
  graphql-kotlin-schema-generator/pom.xml
  graphql-kotlin-spring-server/pom.xml
  pom.xml
Labels: changes: patch, type: bug

#426 [spring-server] fix: Exclude stacktraces when null values are specified for non-null parameters
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponseKtTest.kt
Labels: changes: patch, type: bug

#420 Throw exception on multi-level interface
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidInterfaceException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/filters/superclassFilters.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/InterfaceOfInterfaceTest.kt
Labels: changes: minor, type: enhancement

#433 [spring-server] simplify schema configuration auto configuration
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/SchemaGeneratorConfig.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/NoopSchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/CustomDataFetcherTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederationAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
Labels: changes: minor, type: enhancement

#435 [spring-server] update to use SpringBoot 2.2.0.RELEASE
  graphql-kotlin-spring-server/pom.xml
  pom.xml
Labels: changes: patch, type: dependency changes

#436 [docs] update spring-server configuration details
  docs/server/spring-beans.md
  docs/server/spring-properties.md
Labels: type: documentation

#437 [chore] cleanup of the federation example root pom
  examples/federation/pom.xml
Labels: type: tool update

#438 [chore] continous integration build upgrade
  .github/workflows/maven.yml
  .travis.yml
Labels: type: tool update

#441 [chore] force Github CI Action to use default maven build profile
  .github/workflows/maven.yml
Labels: type: tool update

#444 Upgrade dokka version
  detekt.yml
  pom.xml
Labels: changes: patch, type: dependency changes

#445 [spring-server] use data classes for configuration properties
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/spring/src/main/resources/application.yml
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
  graphql-kotlin-spring-server/src/main/resources/META-INF/spring-configuration-metadata.json
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/FederationConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SubscriptionConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/ContextWebFilterTest.kt
Labels: changes: patch, type: refactor

#448 Update examples.md
  docs/examples.md
Labels: type: documentation

#450 Remove reflections lib in favor of ClassGraph
  graphql-kotlin-federation/pom.xml
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/TestResolvers.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/TestSchema.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/queries/federated/Product.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/queries/simple/NestedQuery.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/queries/simple/SimpleQuery.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/EntityQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/FederatedQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
  graphql-kotlin-schema-generator/pom.xml
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SubTypeMapper.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SubTypeMapperTest.kt
  pom.xml
Labels: changes: patch, type: dependency changes, type: refactor

#453 Add Algolia doc search to the website
  .gitignore
  website/.gitignore
  website/.nvmrc
  website/siteConfig.js
Labels: type: documentation

#455 [docs] update federation docs with more detail
  docs/federated/apollo-federation.md
  docs/federated/federated-schemas.md
  website/sidebars.json
Labels: type: documentation

#451 Fix GH actions PR check
  .github/workflows/maven.yml
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SubTypeMapper.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/TypesCache.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
Labels: changes: patch, type: tool update

#457 [spring-server] make sdl endpoint customizable
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/PlaygroundAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
Labels: changes: minor, type: enhancement

#456 [docs] spring-server documentation updates
  docs/federated/federated-schemas.md
  docs/server/spring-auto-config.md
  docs/server/spring-beans.md
  docs/server/spring-graphql-context.md
  docs/server/spring-properties.md
  website/sidebars.json
Labels: type: documentation

#458 [spring-server] make ContextWebFilter conditionally created
  docs/server/spring-beans.md
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
Labels: changes: minor, type: enhancement

#460 Remove guava for Kotlin builtin decapitalize
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/CustomDirectiveWiringFactory.kt
  graphql-kotlin-schema-generator/pom.xml
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/DirectiveBuilder.kt
Labels: changes: patch, type: dependency changes, type: refactor
