Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-01, with the labels that each got.

#128 doc: update maven central link
  README.md
Labels: changes: no version

#127 refactor: simplify type cache
  example/src/main/kotlin/com/expedia/graphql/sample/extension/CustomSchemaGeneratorHooks.kt
  example/src/main/kotlin/com/expedia/graphql/sample/model/Node.kt
  example/src/main/kotlin/com/expedia/graphql/sample/query/RecursiveQuery.kt
  src/main/kotlin/com/expedia/graphql/exceptions/CouldNotCastToKClassException.kt
  src/main/kotlin/com/expedia/graphql/exceptions/CouldNotGetNameOfKTypeException.kt
  src/main/kotlin/com/expedia/graphql/exceptions/TypeNotSupportedException.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/kParameterExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/kTypeExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
  src/main/kotlin/com/expedia/graphql/generator/types/ListTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KTypeExtensionsKtTest.kt
Labels: changes: major

#130 refactor: use input name in cache
  src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
  src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/kTypeExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
  src/main/kotlin/com/expedia/graphql/generator/types/InputObjectTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/ListTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KTypeExtensionsKtTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/ListTypeTest.kt
Labels: changes: patch

#132 fix: simplify directive wiring
  src/main/kotlin/com/expedia/graphql/DirectiveWiringHelper.kt
  src/main/kotlin/com/expedia/graphql/exceptions/InvalidSchemaDirectiveWiringException.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/graphQLExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/graphQLTypeExtensions.kt
  src/test/kotlin/com/expedia/graphql/DirectiveWiringHelperTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/GraphQLExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/GraphQLTypeExtensionsTest.kt
Labels: changes: minor

#133 test: add more hook tests
  src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
  src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
Labels: changes: patch

#138 refactor: simplify predicate
  example/src/main/kotlin/com/expedia/graphql/sample/validation/DataFetcherExecutionValidator.kt
  src/main/kotlin/com/expedia/graphql/KotlinDataFetcher.kt
  src/main/kotlin/com/expedia/graphql/hooks/DataFetcherExecutionPredicate.kt
  src/test/kotlin/com/expedia/graphql/KotlinDataFetcherTest.kt
  src/test/kotlin/com/expedia/graphql/dataFetchers/DataFetchPredicateTests.kt
Labels: changes: major

#143 fix: recursive interfaces
  src/main/kotlin/com/expedia/graphql/generator/types/InterfaceTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/ObjectTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/integration/NodeGraphTest.kt
  src/test/kotlin/com/expedia/graphql/integration/RecursiveInterfaceTest.kt
  src/test/kotlin/com/expedia/graphql/integration/RecursiveUnionTest.kt
Labels: changes: patch

#145 doc: update readme with example
  README.md
Labels: changes: no version, type: documentation

#144 build: 0.0.33-SNAPSHOT
  example/pom.xml
  pom.xml
Labels: changes: no version

#148 Enable coroutine support in default KotlinDataFetcher
  example/src/main/kotlin/com/expedia/graphql/sample/query/CoroutineQuery.kt
  pom.xml
  src/main/kotlin/com/expedia/graphql/KotlinDataFetcher.kt
Labels: changes: minor

#142 build: travis commits the snapshot updates
  .gitignore
  .travis.yml
  .travis/deploy.sh
  .travis/update-version.sh
Labels: changes: no version

#149 travis: Upgrade to next snapshot (Build 542)
  example/pom.xml
  pom.xml
Labels: changes: no version

#147 test: add property builder unit tests
  src/test/kotlin/com/expedia/graphql/generator/types/PropertyTypeBuilderTest.kt
Labels: changes: no version

#151 An integration test for optional results.
  src/test/kotlin/com/expedia/graphql/integration/OptionalResultsTest.kt
Labels: changes: no version

#152 Enable support for specifying custom DataFetchers
  example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  example/src/main/kotlin/com/expedia/graphql/sample/dataFetchers/CustomDataFetcherFactoryProvider.kt
  example/src/main/kotlin/com/expedia/graphql/sample/extension/CustomSchemaGeneratorHooks.kt
  example/src/main/kotlin/com/expedia/graphql/sample/query/ContextualQuery.kt
  example/src/main/kotlin/com/expedia/graphql/sample/validation/DataFetcherExecutionValidator.kt
  src/main/kotlin/com/expedia/graphql/SchemaGeneratorConfig.kt
  src/main/kotlin/com/expedia/graphql/execution/DataFetcherExecutionPredicate.kt
  src/main/kotlin/com/expedia/graphql/execution/FunctionDataFetcher.kt
  src/main/kotlin/com/expedia/graphql/execution/KotlinDataFetcherFactoryProvider.kt
  src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/PropertyTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
  src/test/kotlin/com/expedia/graphql/execution/CustomDataFetcherTests.kt
  src/test/kotlin/com/expedia/graphql/execution/DataFetchPredicateTests.kt
  src/test/kotlin/com/expedia/graphql/execution/FunctionDataFetcherTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/PropertyTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
  src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
Labels: changes: major

#154 feat: add version number to travis commit message
  .travis/update-version.sh
Labels: changes: no version

#158 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: changes: no version
