Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-03, with the labels that each got.

#187 Create example README
  example/README.md
Labels: type: documentation

#186 docs: update the readme
  README.md
Labels: type: documentation

#183 docs: add release template
  .github/release-drafter.yml
Labels: type: documentation

#192 fix: do not cache GraphQLTypeReference
  src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
  src/test/kotlin/com/expedia/graphql/test/integration/NodeGraphTest.kt
Labels: changes: patch, type: bug

#190 Update example app to use Spring Webflux and GraphQL Playground
  .editorconfig
  example/README.md
  example/pom.xml
  example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  example/src/main/kotlin/com/expedia/graphql/sample/GraphQLRequest.kt
  example/src/main/kotlin/com/expedia/graphql/sample/GraphQLResponse.kt
  example/src/main/kotlin/com/expedia/graphql/sample/QueryHandler.kt
  example/src/main/kotlin/com/expedia/graphql/sample/RoutesConfiguration.kt
  example/src/main/kotlin/com/expedia/graphql/sample/context/MyGraphQLContext.kt
  example/src/main/kotlin/com/expedia/graphql/sample/context/MyGraphQLContextBuilder.kt
  example/src/main/kotlin/com/expedia/graphql/sample/context/MyGraphQLContextWebFilter.kt
  example/src/main/kotlin/com/expedia/graphql/sample/controllers/SDLController.kt
  example/src/main/kotlin/com/expedia/graphql/sample/datafetchers/CustomDataFetcherFactoryProvider.kt
  example/src/main/kotlin/com/expedia/graphql/sample/query/ContextualQuery.kt
  example/src/main/resources/graphql-playground.html
Labels: type: enhancement
