Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-06, with the labels that each got.

#233 Update to latest kotlin and fix incorrect jackson version in the example
  example/pom.xml
  pom.xml
Labels: changes: patch, type: dependency changes

#235 Fixed typo in package name
  example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  example/src/main/kotlin/com/expedia/graphql/sample/RoutesConfiguration.kt
  example/src/main/kotlin/com/expedia/graphql/sample/subscribtions/Subscription.kt
  example/src/main/kotlin/com/expedia/graphql/sample/subscriptions/SimpleSubscription.kt
  example/src/main/kotlin/com/expedia/graphql/sample/subscriptions/Subscription.kt
Labels: type: documentation

#236 fix: update TypeNotSupportedException message
  src/main/kotlin/com/expedia/graphql/exceptions/TypeNotSupportedException.kt
Labels: changes: patch, type: documentation

#232 feat: new hook for modifying object types
  src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
  src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
Labels: changes: minor, type: enhancement

#239 example: add another nested example
  example/src/main/kotlin/com/expedia/graphql/sample/query/NestedQueries.kt
Labels: type: documentation

#242 upgrade to graphql-java 13
  example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/CakeOnlyDirectiveWiring.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/CakeOnlySchemaDirectiveWiring.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/CustomDirective.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/CustomDirectiveWiringFactory.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/DirectiveWiring.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/DirectiveWiringFactory.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/LowercaseDirectiveWiring.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/LowercaseSchemaDirectiveWiring.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/SimpleDirective.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/StringEvalDirectiveWiring.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/StringEvalSchemaDirectiveWiring.kt
  example/src/main/kotlin/com/expedia/graphql/sample/exceptions/CustomDataFetcherExceptionHandler.kt
  example/src/main/kotlin/com/expedia/graphql/sample/extension/CustomSchemaGeneratorHooks.kt
  example/src/main/kotlin/com/expedia/graphql/sample/model/Animal.kt
  example/src/main/kotlin/com/expedia/graphql/sample/query/DirectiveQuery.kt
  example/src/main/kotlin/com/expedia/graphql/sample/query/SimpleQuery.kt
  pom.xml
  src/main/kotlin/com/expedia/graphql/DirectiveWiringHelper.kt
  src/main/kotlin/com/expedia/graphql/annotations/GraphQLDirective.kt
  src/main/kotlin/com/expedia/graphql/directives/KotlinDirectiveWiringFactory.kt
  src/main/kotlin/com/expedia/graphql/directives/KotlinSchemaDirectiveEnvironment.kt
  src/main/kotlin/com/expedia/graphql/directives/KotlinSchemaDirectiveWiring.kt
  src/main/kotlin/com/expedia/graphql/exceptions/InvalidSchemaDirectiveWiringException.kt
  src/main/kotlin/com/expedia/graphql/execution/KotlinDataFetcherFactoryProvider.kt
  src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
  src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/graphQLExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/types/EnumBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/InputObjectBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/InterfaceBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/MutationBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/ObjectBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/PropertyBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/QueryBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/ScalarBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/SubscriptionBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/UnionBuilder.kt
  src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
  src/test/kotlin/com/expedia/graphql/DirectiveWiringHelperTest.kt
  src/test/kotlin/com/expedia/graphql/directives/DirectiveTests.kt
  src/test/kotlin/com/expedia/graphql/directives/KotlinDirectiveWiringFactoryTest.kt
  src/test/kotlin/com/expedia/graphql/directives/KotlinSchemaDirectiveWiringTest.kt
  src/test/kotlin/com/expedia/graphql/execution/CustomDataFetcherTests.kt
  src/test/kotlin/com/expedia/graphql/execution/DataFetchPredicateTests.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/GraphQLExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/DirectiveBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/PropertyBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
  src/test/kotlin/com/expedia/graphql/testSchemaConfig.kt
Labels: changes: major, type: dependency changes
