Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-04, with the labels that each got.

#202 feat: do not cache list types
  src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/kTypeExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KTypeExtensionsKtTest.kt
  src/test/kotlin/com/expedia/graphql/generator/state/TypesCacheTest.kt
Labels: changes: patch, type: enhancement

#205 fix: allow for abstract properties and functions
  src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
Labels: changes: patch, type: bug

#207 FunctionBuilder ignores parameters annotated with GraphQLIgnore
  src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
  src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt
Labels: changes: minor, type: enhancement

#211 Support custom names via @GraphQLName
  src/main/kotlin/com/expedia/graphql/annotations/GraphQLName.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/annotationExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
  src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/AnnotationExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/EnumBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/InputObjectBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/InterfaceBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/ObjectBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/UnionBuilderTest.kt
Labels: changes: minor, type: enhancement
