Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-02, with the labels that each got.

#161 feat: log a better exception on invalid argument types
  src/main/kotlin/com/expedia/graphql/exceptions/CouldNotCastArgumentException.kt
  src/main/kotlin/com/expedia/graphql/exceptions/InvalidInputFieldTypeException.kt
  src/main/kotlin/com/expedia/graphql/execution/FunctionDataFetcher.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/suppressedExtenstions.kt
  src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/execution/FunctionDataFetcherTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KParameterExtensionsKtTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/SuppressedExtenstionsKtTest.kt
Labels: changes: minor

#160 feat: update config settings for subscriptions
  example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  src/main/kotlin/com/expedia/graphql/SchemaGeneratorConfig.kt
  src/main/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/toSchema.kt
  src/test/kotlin/com/expedia/graphql/execution/CustomDataFetcherTests.kt
  src/test/kotlin/com/expedia/graphql/execution/DataFetchPredicateTests.kt
  src/test/kotlin/com/expedia/graphql/generator/DirectiveTests.kt
  src/test/kotlin/com/expedia/graphql/generator/PolymorphicTests.kt
  src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorAsyncTests.kt
  src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
  src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
  src/test/kotlin/com/expedia/graphql/integration/OptionalResultsTest.kt
Labels: changes: major

#163 build: 0.2.1-SNAPSHOT (Travis Build 597)
  example/pom.xml
  pom.xml
Labels: changes: no version

#165 refactor: simplify the deep name logic
  src/main/kotlin/com/expedia/graphql/extensions/deepName.kt
Labels: changes: patch

#164 Update library versions
  detekt.yml
  example/pom.xml
  example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  example/src/main/kotlin/com/expedia/graphql/sample/datafetchers/CustomDataFetcherFactoryProvider.kt
  example/src/main/kotlin/com/expedia/graphql/sample/datafetchers/SpringDataFetcherFactory.kt
  pom.xml
  src/main/kotlin/com/expedia/graphql/SchemaGeneratorConfig.kt
  src/main/kotlin/com/expedia/graphql/exceptions/CouldNotCastArgumentException.kt
  src/main/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilder.kt
Labels: changes: patch

#166 fix: move the default handling of CompletableFuture
  src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
  src/test/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
Labels: changes: patch

#167 feat: standardize casting of GraphQLType
  src/main/kotlin/com/expedia/graphql/exceptions/CouldNotCastGraphQLType.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/graphQLExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/InputObjectTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/InterfaceTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/ObjectTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/PropertyTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/UnionTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/DirectiveWiringHelperTest.kt
  src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorAsyncTests.kt
  src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/AnnotationExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/GraphQLExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
  src/test/kotlin/com/expedia/graphql/generator/filters/SuperclassFiltersKtTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/ObjectTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/ScalarTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
  src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
  src/test/kotlin/com/expedia/graphql/integration/NodeGraphTest.kt
  src/test/kotlin/com/expedia/graphql/integration/OptionalResultsTest.kt
  src/test/kotlin/com/expedia/graphql/integration/RecursiveInterfaceTest.kt
  src/test/kotlin/com/expedia/graphql/integration/RecursiveUnionTest.kt
Labels: changes: minor

#171 Add example of subquery
  example/src/main/kotlin/com/expedia/graphql/sample/query/SubQueries.kt
Labels: type: documentation

#174 feat: allow directives on other types
  example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
  example/src/main/kotlin/com/expedia/graphql/sample/controllers/SDLController.kt
  example/src/main/kotlin/com/expedia/graphql/sample/directives/SimpleDirective.kt
  example/src/main/kotlin/com/expedia/graphql/sample/query/DirectiveQuery.kt
  src/main/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/EnumTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/InputObjectTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/InterfaceTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/UnionTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/generator/types/EnumTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/InputObjectTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/InputObjectTypeTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/InterfaceTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/UnionTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/utils/SimpleDirective.kt
Labels: changes: patch, type: bug

#172 Add question issue template
  .github/ISSUE_TEMPLATE/question.md
Labels: type: documentation

#176 fix: remove directive duplication in the generator
  src/main/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilderTest.kt
Labels: changes: patch, type: bug

#173 feat: pass DataFetcherEnvironment to arguments
  example/src/main/kotlin/com/expedia/graphql/sample/model/ContextualResponse.kt
  example/src/main/kotlin/com/expedia/graphql/sample/query/ContextualQuery.kt
  example/src/main/kotlin/com/expedia/graphql/sample/query/EnvironmentQuery.kt
  src/main/kotlin/com/expedia/graphql/execution/FunctionDataFetcher.kt
  src/main/kotlin/com/expedia/graphql/generator/extensions/kParameterExtensions.kt
  src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/execution/FunctionDataFetcherTest.kt
  src/test/kotlin/com/expedia/graphql/generator/extensions/KParameterExtensionsKtTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilderTest.kt
Labels: changes: minor, type: enhancement

#177 test: add a unit test for missing coverage
  src/test/kotlin/com/expedia/graphql/execution/FunctionDataFetcherTest.kt
Labels: changes: patch

#178 fix: travis deployments are not running
  .travis.yml
Labels: type: tool update

#180 build: don't run deploy on master branch push
  .travis.yml
Labels: type: tool update

#179 build: 0.2.6-SNAPSHOT (Travis Build 642)
  example/pom.xml
  pom.xml
Labels: changes: patch

#181 fix: add directives on enum values
  example/src/main/kotlin/com/expedia/graphql/sample/model/Animal.kt
  src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
  src/main/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilder.kt
  src/main/kotlin/com/expedia/graphql/generator/types/EnumTypeBuilder.kt
  src/test/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/EnumTypeBuilderTest.kt
  src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
  src/test/kotlin/com/expedia/graphql/utils/CustomDirective.kt
Labels: changes: patch, type: bug
