Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-12, with the labels that each got.

#495 Enable Github Action for PR checks
  .github/workflows/maven.yml
  .github/workflows/pr-check.yml
Labels: type: tool update

#497 Update PR check formatting
  .github/workflows/pr-check.yml
Labels: type: tool update

#501 Add unit tests for renaming input type fields
  docs/customizing-schemas/renaming-fields.md
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/InputObjectBuilderTest.kt
Labels: changes: patch

#502 Log schema with starting newline
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederationAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
Labels: changes: patch

#503 Update interface docs
  docs/writing-schemas/interfaces.md
Labels: type: documentation

#504 Update publish-docs to use github tokens
  .github/workflows/publish-docs.yml
Labels: type: tool update

#505 Update documenting-fields.md
  docs/customizing-schemas/documenting-fields.md
Labels: type: documentation

#511 Revert "Update publish-docs to use github tokens"
  .github/workflows/publish-docs.yml
Labels: type: bug, type: tool update

#510 fix subscriptions by not removing the ak subscription when one of the…
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
Labels: changes: patch, type: refactor

#513 Do not close session on subscription GQL_STOP
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
Labels: changes: patch, type: refactor

#514 Add perf tests to validate subscription performance
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  perf-tests/.gitignore
  perf-tests/.nvmrc
  perf-tests/README.md
  perf-tests/graphql-mutation.yml
  perf-tests/graphql-query.yml
  perf-tests/graphql-subscription.yml
  perf-tests/package-lock.json
  perf-tests/package.json
Labels: changes: patch, type: refactor

#515 Fix subscription caching logic
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionState.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionStateTest.kt
Labels: changes: patch, type: bug

#519 [build] enforce jacoco coverage check at build time
  graphql-kotlin-federation/pom.xml
  graphql-kotlin-schema-generator/pom.xml
  graphql-kotlin-spring-server/pom.xml
Labels: type: tool update

#520 Prevent starting second subscription with the same id
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionState.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
Labels: changes: patch, type: enhancement

#522 Update subscription documentation
  docs/execution/subscriptions.md
  docs/server/subscriptions.md
  website/sidebars.json
Labels: type: documentation

#528 Add Slack badge link
  README.md
Labels: type: documentation

#525 [spring-server] default data fetcher should use Jackson object mapper from spring context
  docs/server/spring-beans.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/datafetchers/CustomDataFetcherFactoryProvider.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorConfig.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/SchemaGeneratorConfig.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/KotlinDataFetcherFactoryProvider.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/CustomDataFetcherTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederationAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/DataFetcherIT.kt
Labels: changes: major, type: enhancement

#530 [generator] update generator hooks to include target kclass info
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/MutationBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/QueryBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/MutationBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/QueryBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
Labels: changes: major, type: enhancement

#531 Fix recursive input schema
  detekt.yml
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorProvidesDirectiveTest.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/TypeBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/TypesCache.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ArgumentBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/DirectiveBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/EnumBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InputObjectBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InputPropertyBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ListBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/MutationBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ObjectBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/PropertyBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/QueryBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/UnionBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ObjectBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/UnionBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/OutputTypeWithRecursiveInputTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/RecursiveInputTest.kt
Labels: changes: minor, type: bug, type: refactor

#532 Refactor schema generator to remove cyclic dependencies
  detekt.yml
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorKeyDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorProvidesDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorRequiresDirectiveTest.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ArgumentBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/DirectiveBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/EnumBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InputObjectBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InputPropertyBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ListBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/MutationBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ObjectBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/PropertyBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/QueryBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilder.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/UnionBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ArgumentBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/DirectiveBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/EnumBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/InputObjectBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/InputPropertyBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ListBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/MutationBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ObjectBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/PropertyBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/QueryBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilderTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/UnionBuilderTest.kt
Labels: changes: major, type: refactor
