Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2019-11, with the labels that each got.

#464 [docs] Add new blogs & videos page
  docs/blogs-and-videos.md
  website/sidebars.json
Labels: type: documentation

#465 [docs] Add GraphQL Summit 2019 video
  docs/blogs-and-videos.md
Labels: type: documentation

#467 Update mvn wrapper version
  .mvn/wrapper/maven-wrapper.properties
Labels: type: tool update

#466 Update dependency versions
  examples/federation/base-app/src/test/kotlin/com/expediagroup/graphql/examples/model/WidgetTest.kt
  examples/federation/extend-app/src/test/kotlin/com/expediagroup/graphql/examples/extend/WidgetTest.kt
  examples/spring/pom.xml
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
  pom.xml
Labels: changes: patch, type: dependency changes, type: tool update

#469 Create publish GH Packages action
  .github/workflows/publish-package.yml
Labels: type: tool update

#476 Validate subscription return type
  graphql-kotlin-schema-generator/pom.xml
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidSubscriptionTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilderTest.kt
  pom.xml
Labels: changes: patch, type: bug

#481 [chore] move dokka configuration to release profile
  pom.xml
Labels: type: tool update

#482 Delete publish package GH Action
  .github/workflows/publish-package.yml
Labels: type: tool update

#480 update to next major release
  examples/federation/base-app/pom.xml
  examples/federation/extend-app/pom.xml
  examples/federation/pom.xml
  examples/pom.xml
  examples/spring/pom.xml
  graphql-kotlin-federation/pom.xml
  graphql-kotlin-schema-generator/pom.xml
  graphql-kotlin-spring-server/pom.xml
  pom.xml
Labels: changes: major

#478 BREAKING CHANGE: Remove DataFetcherExecutionPredicate
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/datafetchers/CustomDataFetcherFactoryProvider.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/extension/CustomSchemaGeneratorHooks.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/validation/DataFetcherExecutionValidator.kt
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/extension/CustomSchemaGeneratorHooksTest.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorConfig.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/SchemaGeneratorConfig.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/DataFetcherExecutionPredicate.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/KotlinDataFetcherFactoryProvider.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/CustomDataFetcherTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/DataFetchPredicateTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederationAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
Labels: changes: major, type: enhancement

#473 [federation] federated type resolvers should have access to environment
  examples/federation/extend-app/src/main/kotlin/com/expediagroup/graphql/examples/extend/Widget.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/FederatedTypeResolver.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/resolvers.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/TestResolvers.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/EntityQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ResolversKtTest.kt
Labels: changes: major, type: enhancement

#486 Update doc links
  docs/customizing-schemas/directives.md
  docs/examples.md
  docs/execution/data-fetching-environment.md
  docs/getting-started.md
  docs/writing-schemas/nested-queries.md
  docs/writing-schemas/scalars.md
Labels: type: documentation

#488 Update website depencies and license notice
  website/core/Footer.js
  website/package-lock.json
  website/package.json
  website/sidebars.json
  website/siteConfig.js
Labels: type: documentation

#490 Add slack info to README
  README.md
Labels: type: documentation

#487 Allow for subscription request on the same endpoint
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/SubscriptionRoutesConfigurationIT.kt
Labels: changes: patch, type: bug

#491 Update the spring server docs
  docs/getting-started.md
  docs/server/spring-overview.md
  website/sidebars.json
Labels: type: documentation
