Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2020-01, with the labels that each got.

#536 GitHub Actions checkout v2
  .github/workflows/pr-check.yml
  .github/workflows/publish-docs.yml
Labels: type: tool update

#539 Update spring server overview page
  docs/assets/spring-initializer.png
  docs/blogs-and-videos.md
  docs/examples.md
  docs/getting-started.md
  docs/spring-server/spring-beans.md
  docs/spring-server/spring-graphql-context.md
  docs/spring-server/spring-overview.md
  docs/spring-server/spring-properties.md
  docs/spring-server/subscriptions.md
  website/sidebars.json
Labels: type: documentation

#540 Refactor federation validation unit tests
  graphql-kotlin-federation/pom.xml
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaValidator.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ExtendsDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ExternalDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/KeyDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ProvidesDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/RequiresDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/extensions/GraphQLDirectiveContainerExtensions.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateKeySetField.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateProvidesDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateRequiresDirective.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaValidatorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/federationDirectives.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorKeyDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorProvidesDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorRequiresDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateDirectiveKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateFieldSelectionKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateKeySetFieldKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateProvidesDirectiveKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateRequiresDirectiveKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/key/FederatedKeyDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/provides/FederatedProvidesDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/requires/FederatedRequiresDirectiveTest.kt
  graphql-kotlin-schema-generator/pom.xml
Labels: changes: patch, type: refactor

#542 [docs] information about execution and how to return partial data
  docs/execution/contextual-data.md
  docs/execution/data-fetching-environment.md
  docs/execution/exceptions.md
  docs/execution/fetching-data.md
  docs/execution/subscriptions.md
  docs/writing-schemas/scalars.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataAndErrorsQuery.kt
  website/sidebars.json
Labels: type: documentation

#545 [generator] Rename internal files
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateDirective.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateEnum.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateFunction.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputObject.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputProperty.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateList.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateMutation.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateObject.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateProperty.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateScalar.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateSubscription.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateUnion.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/ClassScannerTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateEnumTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInputObjectTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInputPropertyTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInterfaceTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateListTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateMutationTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateObjectTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateQueryTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateScalarTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateSubscriptionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateUnionTest.kt
Labels: changes: patch, type: refactor

#546 Support List for input arguments
  docs/writing-schemas/lists.md
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/CouldNotCastArgumentException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/TypesCache.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KParameterExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateListTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateObjectTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateUnionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
Labels: changes: minor, type: enhancement

#548 [federation] federated directives integration tests
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_1/FederatedMissingKey.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_2/KeyMissingFieldSelection.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_3/InvalidKey.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_4/BaseKeyReferencingExternalFields.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_5/ExternalKeyReferencingLocalField.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_6/KeyReferencingList.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_7/KeyReferencingInterface.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_8/KeyReferencingUnion.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/failure/_9/NestedKeyReferencingScalar.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/success/_1/SimpleKey.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/success/_2/SimpleFederatedKey.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/success/_3/KeyWithMultipleFields.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/success/_4/FederatedKeyWithMultipleFields.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/success/_5/KeyWithNestedFields.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/key/success/_6/FederatedKeyWithNestedFields.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/provides/failure/_1/ProvidesLocalType.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/provides/failure/_2/ProvidesLocalField.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/provides/failure/_3/ProvidesInterface.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/provides/failure/_4/ProvidesListField.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/provides/failure/_5/ProvidesInterfaceField.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/provides/success/_1/SimpleProvides.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/provides/success/_2/ProvidesList.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/requires/failure/_1/RequiresLocalField.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/requires/failure/_2/RequiresNonExistentField.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/requires/failure/_3/RequiresOnLocalType.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/integration/requires/success/_1/SimpleRequires.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateFieldSelectionKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/FederatedKeyDirectiveIT.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/FederatedProvidesDirectiveIT.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/FederatedRequiresDirectiveIT.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/federatedTestConfig.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/key/FederatedKeyDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/provides/FederatedProvidesDirectiveTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/requires/FederatedRequiresDirectiveTest.kt
Labels: changes: patch, type: tool update

#549 [build] configure GH action PR check for documentation updates
  .github/workflows/pr-check-docs.yml
Labels: type: tool update

#551 [build] split GH continuous integration action in PR and master build
  .github/workflows/continuous-integration.yml
  .github/workflows/pr-check-docs.yml
  .github/workflows/pr-check.yml
  README.md
Labels: type: tool update

#552 [build] fix release workflow
  .github/workflows/release.yml
Labels: type: tool update

#553 [build] fix release workflow
  .github/workflows/release.yml
Labels: type: tool update

#554 [build] attempt to explicitly read tag version
  .github/workflows/release.yml
Labels: type: tool update

#555 Changed annotation processor to use kapt
  graphql-kotlin-spring-server/build.gradle.kts
  graphql-kotlin-spring-server/src/main/resources/META-INF/spring-configuration-metadata.json
Labels: type: tool update

#559 [build] add missing credentials to nexus-staging plugin config
  .github/workflows/release.yml
  build.gradle.kts
Labels: type: tool update

#560 [build] explicitly set package group on nexus staging plugin
  build.gradle.kts
Labels: type: tool update

#562 [build] use proper npm command for docs PR check
  .github/workflows/pr-check-docs.yml
Labels: type: tool update

#567 [build] apply nexus-publish plugin on ALL projects
  build.gradle.kts
Labels: type: tool update

#569 [federation] Move vals and functions to internal scope
  .gitignore
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Any.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Entity.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_FieldSet.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Service.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidator.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorTest.kt
Labels: changes: patch, type: refactor

#568 Upgrade to graphql-java 14
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/query/PolymorphicQueryIT.kt
  gradle.properties
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/queries/federated/Product.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/ServiceTest.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinDirectiveWiringFactory.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/CouldNotCastGraphQLSchemaElement.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/graphQLExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/KGraphQLType.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/TypesCache.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/KotlinDirectiveWiringFactoryTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/DeepNameKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorAsyncTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/KGraphQLTypeTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/TypesCacheTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateListTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
Labels: changes: major

#571 Update dependency versions and docs
  CONTRIBUTING.md
  docs/examples.md
  examples/federation/README.md
  examples/federation/base-app/README.md
  examples/federation/extend-app/README.md
  examples/spring/README.md
  gradle.properties
  graphql-kotlin-schema-generator/build.gradle.kts
Labels: changes: patch, type: dependency changes

#572 [build] Remove travis-ci
  .travis.yml
  .travis/deploy.sh
  .travis/settings.xml
  .travis/update-version.sh
Labels: type: tool update

#575 [build] Update nexus publish timeout
  build.gradle.kts
  gradle.properties
Labels: type: tool update

#576 Remove perf-tests directory
  perf-tests/.gitignore
  perf-tests/.nvmrc
  perf-tests/README.md
  perf-tests/graphql-mutation.yml
  perf-tests/graphql-query.yml
  perf-tests/graphql-subscription.yml
  perf-tests/package-lock.json
  perf-tests/package.json
Labels: type: tool update

#577 Update DataFetchingEnvironment docs
  docs/execution/data-fetching-environment.md
  docs/execution/exceptions.md
  docs/execution/fetching-data.md
  docs/spring-server/spring-beans.md
  docs/writing-schemas/scalars.md
Labels: type: documentation

#579 Set gradle prop to fix release process
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: type: tool update

#578 Remove actions/cache from release
  .github/workflows/release.yml
Labels: type: tool update

#544 Add Apollo Subscription Hooks
  docs/spring-server/subscriptions.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/context/MyGraphQLContext.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/context/MyGraphQLContextFactory.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/MySubscriptionHooks.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionHooks.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionState.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
Labels: changes: minor, type: enhancement

#580 Fixed URL to Subscription example
  docs/spring-server/subscriptions.md
Labels: type: documentation

#581 Add release notes step in GH Actions
  .github/workflows/continuous-integration.yml
Labels: type: tool update

#582 feat: open FunctionDataFetcher methods for extension
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
Labels: changes: minor, type: enhancement
