Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2020-09, with the labels that each got.

#857 Update gradle wrapper in examples
  examples/gradle/wrapper/gradle-wrapper.jar
  examples/gradle/wrapper/gradle-wrapper.properties
  examples/gradlew
  examples/gradlew.bat
Labels: type: tool update

#845 Fix subscriptions messaging and tests
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/dataloaders/CompanyService.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/dataloaders/DataLoaderConfiguration.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataLoaderQuery.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt
  gradle.properties
  graphql-kotlin-spring-server/build.gradle.kts
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionState.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/extensions/responseExtensions.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionStateTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/extensions/GeneratorExtensionsKtTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/SubscriptionRoutesConfigurationIT.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojoTest.kt
Labels: changes: patch, type: bug

#852 Update docs on library release
  .github/workflows/release.yml
  website/package-lock.json
  website/package.json
  website/pages/en/versions.js
Labels: type: documentation

#859 [examples] update GraphQL client examples to use latest code
  examples/client/gradle-client/build.gradle.kts
  examples/client/gradle-client/gradle/wrapper/gradle-wrapper.jar
  examples/client/gradle-client/gradle/wrapper/gradle-wrapper.properties
  examples/client/gradle-client/gradlew
  examples/client/gradle-client/gradlew.bat
  examples/client/gradle-client/src/main/kotlin/com/expediagroup/graphql/examples/client/Application.kt
  examples/client/gradle-client/src/main/kotlin/com/expediagroup/graphql/examples/client/UUIDScalarConverter.kt
  examples/client/gradle-client/src/main/resources/ExampleQuery.graphql
  examples/client/maven-client/README.md
  examples/client/maven-client/pom.xml
  examples/client/maven-client/src/main/kotlin/com/expediagroup/graphql/examples/client/Application.kt
  examples/client/maven-client/src/main/kotlin/com/expediagroup/graphql/examples/client/UUIDScalarConverter.kt
  examples/client/maven-client/src/main/resources/ExampleQuery.graphql
  examples/client/server/build.gradle.kts
  examples/client/server/gradle/wrapper/gradle-wrapper.jar
  examples/client/server/gradle/wrapper/gradle-wrapper.properties
  examples/client/server/gradlew
  examples/client/server/gradlew.bat
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/SimpleQueries.kt
Labels: changes: patch

#861 Remove federated type registry
  docs/federated/federated-schemas.md
  docs/federated/type-resolution.md
  docs/spring-server/spring-beans.md
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/hooks/CustomFederationSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/FederatedTypeRegistry.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/resolvers.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/TestSchema.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/EntityQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ResolversKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/federatedTestConfig.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederatedSchemaAutoConfiguration.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/FederationConfigurationTest.kt
Labels: changes: major, type: enhancement

#862 Add separate configuration for SDL route
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLRoutesConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/PlaygroundRouteConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SdlRouteConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
Labels: changes: patch, type: refactor

#865 [client] Remove duplicate header
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/introspectSchema.kt
Labels: changes: patch, type: bug

#869 [client] Remove duplicate accept header
  clients/graphql-kotlin-ktor-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLKtorClient.kt
Labels: changes: patch, type: bug

#867 [3.x.x][client] Remove duplicate header
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/introspectSchema.kt
Labels: changes: patch, type: bug

#870 Fix issue with GraphQLName on properties
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/NestedQueries.kt
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/query/NestedQueriesIT.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateProperty.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
Labels: changes: patch, type: bug

#871 [docs] Add a comparison to graphql-java
  docs/graphql-java-comparison.md
  website/sidebars.json
Labels: type: documentation

#878 Add dependency for security alert
  website/package-lock.json
  website/package.json
Labels: type: dependency changes, type: documentation

#883 [client] fix generation of duplicate classes
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/resources/testSchema.graphql
Labels: changes: patch, type: bug

#884 [client][3.x.x] fix generation of duplicate classes
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/resources/testSchema.graphql
Labels: changes: patch, type: bug

#888 README: fix broken URL
  README.md
Labels: type: documentation

#887 Refactor federation code for readability
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Entity.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/FederatedQueryResolverTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/EntityTest.kt
Labels: changes: patch, type: refactor

#891 Start each subscription with init message
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt
Labels: type: documentation

#889 [client] Throw error on non-successful HTTP responses
  clients/graphql-kotlin-ktor-client/src/test/kotlin/com/expediagroup/graphql/client/GraphQLKtorClientTest.kt
  clients/graphql-kotlin-spring-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLWebClient.kt
  clients/graphql-kotlin-spring-client/src/test/kotlin/com/expediagroup/graphql/client/GraphQLWebClientTest.kt
Labels: changes: patch, type: bug
