Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2020-04, with the labels that each got.

#650 Upload graphql-kotlin text logo
  website/static/img/graphql-kotlin.png
Labels: type: documentation

#653 [generator] allow disabling introspection query
  docs/customizing-schemas/generator-config.md
  docs/execution/introspection.md
  docs/spring-server/spring-properties.md
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorConfig.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/SchemaGeneratorConfig.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederationAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/DataFetcherIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/IntrospectionIT.kt
  website/sidebars.json
Labels: changes: minor, type: enhancement

#656 [spring] Refactor config classes and internal functions
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederatedSchemaAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/PlaygroundAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/extensions/generatorExtensions.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt
Labels: changes: patch, type: refactor

#657 Add bean factory example and docs
  docs/writing-schemas/nested-fields.md
  docs/writing-schemas/nested-queries.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/hooks/CustomSchemaGeneratorHooks.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/TopLevelBeanFactoryQuery.kt
  website/sidebars.json
Labels: type: documentation

#669 [generator] support returning GraphQL ID scalar from functions
  docs/writing-schemas/scalars.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateFunction.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
Labels: changes: patch, type: bug

#670 [generator] support returning GraphQL ID scalar from functions 1.x.x
  .github/workflows/maven.yml
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilderTest.kt
Labels: changes: patch, type: bug

#671 new gradle plugin with introspect schema task
  build.gradle.kts
  docs/plugins/gradle-plugin.md
  gradle.properties
  plugins/graphql-kotlin-gradle-plugin/README.md
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/KotlinExtension.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLIntrospectSchemaTask.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/resources/introspectionResult.json
  plugins/graphql-kotlin-plugin-core/README.md
  plugins/graphql-kotlin-plugin-core/build.gradle.kts
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com.expediagroup.graphql.plugin/introspectSchema.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/IntrospectSchemaTest.kt
  plugins/graphql-kotlin-plugin-core/src/test/resources/introspectionResult.json
  settings.gradle.kts
  website/sidebars.json
Labels: changes: minor, type: documentation

#673 Allow for trailing slashes on context filter
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/ContextWebFilterTest.kt
Labels: changes: patch, type: bug

#674 new Maven plugin with introspect schema mojo
  .github/workflows/pr-check.yml
  docs/plugins/gradle-plugin.md
  docs/plugins/maven-plugin.md
  plugins/graphql-kotlin-maven-plugin/.mvn/wrapper/MavenWrapperDownloader.java
  plugins/graphql-kotlin-maven-plugin/.mvn/wrapper/maven-wrapper.jar
  plugins/graphql-kotlin-maven-plugin/.mvn/wrapper/maven-wrapper.properties
  plugins/graphql-kotlin-maven-plugin/README.md
  plugins/graphql-kotlin-maven-plugin/build.gradle.kts
  plugins/graphql-kotlin-maven-plugin/mvnw
  plugins/graphql-kotlin-maven-plugin/mvnw.cmd
  plugins/graphql-kotlin-maven-plugin/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/introspect-schema/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/introspect-schema/src/test/kotlin/com/expediagroup/graphql/plugin/maven/IntrospectSchemaMojoTest.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/settings.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/introspectionResult.json
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/mappings/introspection.json
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com.expediagroup.graphql.plugin.maven/IntrospectSchemaMojo.kt
  settings.gradle.kts
  website/sidebars.json
Labels: changes: minor, type: documentation

#677 [server] GraphQL Error response type should allow null locations
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLError.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLErrorTest.kt
Labels: changes: major, type: bug

#681 [build] dropping idea plugin as it keeps messing up my workspace
  build.gradle.kts
Labels: type: tool update

#678 [generator] explicitly escape special characters in SDL
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/query/SimpleQuery.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensions.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
Labels: changes: patch, type: bug

#683 [client] new GraphQL Client module and code-generation logic
  graphql-kotlin-client/README.md
  graphql-kotlin-client/build.gradle.kts
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLResult.kt
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/converter/ScalarConverter.kt
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/DownloadSDLMojo.kt
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/IntrospectSchemaMojo.kt
  plugins/graphql-kotlin-plugin-core/README.md
  plugins/graphql-kotlin-plugin-core/build.gradle.kts
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/downloadSchema.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generateClient.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGeneratorConfig.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGeneratorContext.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLCustomScalarTypeAlias.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLCustomScalarTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLEnumTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLInputObjectTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLInterfaceTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLObjectTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLUnionTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateInterfaceTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generatePropertySpecs.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateVariableTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/introspectSchema.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLTestUtils.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt
  settings.gradle.kts
Labels: changes: minor
