Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2020-05, with the labels that each got.

#688 [plugins] new generate client Gradle task and Maven mojo
  README.md
  docs/getting-started.md
  docs/plugins/gradle-plugin.md
  docs/plugins/maven-plugin.md
  plugins/graphql-kotlin-gradle-plugin/README.md
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLDownloadSDLTask.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTask.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLIntrospectSchemaTask.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/resources/testQuery.graphql
  plugins/graphql-kotlin-gradle-plugin/src/test/resources/testResponse.json
  plugins/graphql-kotlin-maven-plugin/README.md
  plugins/graphql-kotlin-maven-plugin/build.gradle.kts
  plugins/graphql-kotlin-maven-plugin/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/main/resources/ExampleQuery.graphql
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/schema.graphql
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/src/main/resources/ExampleQuery.graphql
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojoTest.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/response.json
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/mappings/query.json
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojo.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generatePropertySpecs.kt
Labels: changes: minor, type: documentation, type: enhancement

#690 [build] configure gradle publish plugin
  .github/workflows/release.yml
  build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
Labels: type: tool update

#694 [build] exclude plugins directory from list of projects
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-maven-plugin/build.gradle.kts
  settings.gradle.kts
Labels: type: tool update

#696 [build] explicitly disable maven-publish tasks for gradle plugin
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
Labels: type: tool update

#699 fix gradle plugin badge
  plugins/graphql-kotlin-gradle-plugin/README.md
Labels: type: documentation

#700 Remove GraphQLID annotation for ID class
  docs/writing-schemas/annotations.md
  docs/writing-schemas/scalars.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/annotations/GraphQLID.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/annotationExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kPropertyExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateFunction.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateGraphQLType.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputProperty.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateProperty.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateScalar.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/types/ID.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/AnnotationExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KPropertyExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/TypesCacheTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateScalarTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/NodeGraphTest.kt
Labels: changes: major, type: enhancement

#702 Add extends directive if not defined
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ExtendsDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ExternalDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/FieldSet.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/KeyDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ProvidesDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/RequiresDirective.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/extensions/graphQLSchemaExtensions.kt
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateDirective.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/extensions/GraphQLDirectiveContainerExtensionsKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/extensions/GraphQLSchemaExtensionsKtTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/AnyTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/EntityTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/FieldSetTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/ServiceTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateProvidesDirectiveKtTest.kt
Labels: changes: patch, type: bug

#703 Run CI on support branches
  .github/workflows/continuous-integration.yml
Labels: type: tool update

#704 [build] update release process to publish Gradle plugin after sonatype publish
  .github/workflows/release.yml
  build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
Labels: type: tool update

#708 [build] update to 3.0.0-SNAPSHOT
  gradle.properties
Labels: type: tool update

#709 GraphQL client fixes
  graphql-kotlin-client/README.md
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojo.kt
Labels: changes: patch, type: bug

#712 docs: add recipe for using willGenerateGraphQLType with java enums
  docs/writing-schemas/enums.md
Labels: type: documentation

#711 [plugin] update generated GraphQL client execute query method
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt
Labels: changes: patch

#713 [plugin] fix generate client MOJO converter parameter
  docs/plugins/gradle-plugin.md
  plugins/graphql-kotlin-gradle-plugin/README.md
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTask.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/main/kotlin/com/example/UUIDScalarConverter.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojo.kt
Labels: changes: patch, type: bug

#714 [docs] GraphQL client documentation and configuration fixes
  docs/client/client-customization.md
  docs/client/client-features.md
  docs/client/client-overview.md
  graphql-kotlin-client/README.md
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
  plugins/graphql-kotlin-gradle-plugin/README.md
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
  plugins/graphql-kotlin-maven-plugin/README.md
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt
  website/sidebars.json
Labels: changes: patch, type: bug, type: documentation

#716 example client project
  docs/client/client-overview.md
  examples/README.md
  examples/client/README.md
  examples/client/gradle-client/README.md
  examples/client/gradle-client/build.gradle.kts
  examples/client/gradle-client/src/main/kotlin/com/expediagroup/graphql/examples/client/Application.kt
  examples/client/gradle-client/src/main/kotlin/com/expediagroup/graphql/examples/client/UUIDScalarConverter.kt
  examples/client/gradle-client/src/main/resources/AddObjectMutation.graphql
  examples/client/gradle-client/src/main/resources/DeleteObjectMutation.graphql
  examples/client/gradle-client/src/main/resources/ExampleQuery.graphql
  examples/client/gradle-client/src/main/resources/HelloWorldQuery.graphql
  examples/client/gradle-client/src/main/resources/RetrieveObjectQuery.graphql
  examples/client/gradle-client/src/main/resources/UpdateObjectMutation.graphql
  examples/client/maven-client/.mvn/wrapper/MavenWrapperDownloader.java
  examples/client/maven-client/.mvn/wrapper/maven-wrapper.jar
  examples/client/maven-client/.mvn/wrapper/maven-wrapper.properties
  examples/client/maven-client/README.md
  examples/client/maven-client/mvnw
  examples/client/maven-client/mvnw.cmd
  examples/client/maven-client/pom.xml
  examples/client/maven-client/src/main/kotlin/com/expediagroup/graphql/examples/client/Application.kt
  examples/client/maven-client/src/main/kotlin/com/expediagroup/graphql/examples/client/UUIDScalarConverter.kt
  examples/client/maven-client/src/main/resources/AddObjectMutation.graphql
  examples/client/maven-client/src/main/resources/DeleteObjectMutation.graphql
  examples/client/maven-client/src/main/resources/ExampleQuery.graphql
  examples/client/maven-client/src/main/resources/HelloWorldQuery.graphql
  examples/client/maven-client/src/main/resources/RetrieveObjectQuery.graphql
  examples/client/maven-client/src/main/resources/UpdateObjectMutation.graphql
  examples/client/server/README.md
  examples/client/server/build.gradle.kts
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/SimpleMutations.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/SimpleQueries.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/model/BasicInterface.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/model/BasicUnion.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/model/CustomEnum.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/model/NestedObject.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/model/ScalarWrapper.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/model/SimpleArgument.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/repository/BasicObjectRepository.kt
  examples/client/server/src/main/resources/application.yml
Labels: type: documentation

#717 [build] publish Gradle plugin to Maven Central
  plugins/graphql-kotlin-gradle-plugin/README.md
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
Labels: type: tool update

#719 [plugin] update Maven Mojo names to follow hyphen-name
  docs/plugins/maven-plugin.md
  examples/client/maven-client/pom.xml
  plugins/graphql-kotlin-maven-plugin/README.md
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/download-sdl/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-test-client/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/integration/introspect-schema/pom.xml
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/DownloadSDLMojo.kt
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojo.kt
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateTestClientMojo.kt
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/IntrospectSchemaMojo.kt
Labels: changes: major

#720 [docs] add generate test client example documentation and cleanup invalid parameters
  docs/plugins/gradle-plugin.md
  docs/plugins/maven-plugin.md
  plugins/graphql-kotlin-gradle-plugin/README.md
Labels: type: documentation

#724 [plugins] Update Gradle plugin extension to separate client and schema generation
  docs/plugins/gradle-plugin.md
  examples/client/gradle-client/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
Labels: type: refactor

#725 Update codecov config
  .github/workflows/continuous-integration.yml
Labels: type: tool update

#726 Move id to scalars package
  docs/writing-schemas/scalars.md
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/SimpleQueries.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/model/ScalarWrapper.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateScalar.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/scalars/ID.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateScalarTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/NodeGraphTest.kt
  plugins/graphql-kotlin-maven-plugin/pom.xml
Labels: changes: major

#727 Create SECURITY.md
  SECURITY.md
Labels: type: documentation

#731 update to graphql-java 15.0
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/LowercaseSchemaDirectiveWiring.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/SpecificValueOnlySchemaDirectiveWiring.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/StringEvalSchemaDirectiveWiring.kt
  gradle.properties
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/AnyTest.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinFieldDirectiveEnvironment.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensions.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/introspectSchema.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/IntrospectSchemaTest.kt
Labels: changes: minor, type: dependency changes

#732 [generator] allow interfaces to implement other interfaces
  graphql-kotlin-schema-generator/build.gradle.kts
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidInterfaceException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInterfaceTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/InterfaceOfInterfaceTest.kt
Labels: changes: patch, type: enhancement

#729 graphql-kotlin-types
  README.md
  docs/client/client-overview.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataAndErrorsQuery.kt
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/query/DataAndErrorsQueryIT.kt
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt
  graphql-kotlin-client/build.gradle.kts
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/NodeGraphTest.kt
  graphql-kotlin-spring-server/build.gradle.kts
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/KotlinDataFetcherExceptionHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLError.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/QueryHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandler.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/extensions/requestExtensions.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/extensions/responseExtensions.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/operations/Mutation.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/operations/Query.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/operations/Subscription.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/ContextWebFilterTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/GraphQLContextFactoryIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/KotlinDataFetcherExceptionHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLErrorTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/DataFetcherIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/IntrospectionIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/QueryHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/extensions/GeneratorExtensionsKtTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/extensions/RequestExtensionsKtTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/extensions/ResponseExtensionsKtTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/instrumentation/InstrumentationIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/SubscriptionRoutesConfigurationIT.kt
  graphql-kotlin-types/README.md
  graphql-kotlin-types/build.gradle.kts
  graphql-kotlin-types/src/main/kotlin/com/expediagroup/graphql/types/GraphQLError.kt
  graphql-kotlin-types/src/main/kotlin/com/expediagroup/graphql/types/GraphQLRequest.kt
  graphql-kotlin-types/src/main/kotlin/com/expediagroup/graphql/types/GraphQLResponse.kt
  graphql-kotlin-types/src/main/kotlin/com/expediagroup/graphql/types/SourceLocation.kt
  graphql-kotlin-types/src/test/kotlin/com/expediagroup/graphql/types/GraphQLErrorTest.kt
  graphql-kotlin-types/src/test/kotlin/com/expediagroup/graphql/types/GraphQLRequestTest.kt
  graphql-kotlin-types/src/test/kotlin/com/expediagroup/graphql/types/GraphQLResponseTest.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt
  settings.gradle.kts
Labels: changes: major

#733 [build] fix publishing of Gradle plugin marker
  build.gradle.kts
Labels: type: tool update
