Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2020-02, with the labels that each got.

#587 Allow additional types to be added with custom SchemaGenerator
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateProvidesDirective.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/EntityTest.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/graphqlTypeExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateGraphQLType.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateObject.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateUnion.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphqlTypeExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/filters/SuperclassFiltersKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
Labels: changes: patch, type: refactor

#591 [generator] deprecated directive cleanup
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/query/SimpleQuery.kt
  examples/federation/gateway/.gitignore
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/DeprecatedDirectiveExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
Labels: changes: patch, type: refactor

#593 Allow updating custom additional types
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
Labels: changes: minor, type: enhancement

#583 Add example stress query
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/TrackTimesInvoked.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/instrumentation/TrackTimesInvokedInstrumentation.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/StressQuery.kt
Labels: type: documentation

#594 Add docs for new schema generator feature
  docs/customizing-schemas/advanced-features.md
  docs/customizing-schemas/deprecating-schema.md
  docs/customizing-schemas/directives.md
  docs/writing-schemas/annotations.md
  website/sidebars.json
Labels: type: documentation

#599 [docs] example usage of Reactor Mono
  docs/execution/async-models.md
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/hooks/CustomFederationSchemaGeneratorHooks.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/CustomDataFetcherFactoryProvider.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/CustomFunctionDataFetcher.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/SpringDataFetcherFactory.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/hooks/CustomSchemaGeneratorHooks.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/AsyncQuery.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/query/AsyncQueryIT.kt
Labels: type: documentation

#606 Upgrade dependencies
  gradle.properties
  graphql-kotlin-schema-generator/build.gradle.kts
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorAsyncTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateSubscriptionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/utils/FunctionReturnTypesKtTest.kt
Labels: changes: patch, type: dependency changes

#609 Update READMEs and example docs
  README.md
  examples/README.md
  examples/federation/README.md
  examples/federation/gateway/.gitignore
  examples/federation/gateway/.nvmrc
  examples/federation/gateway/README.md
  examples/federation/gateway/index.js
  examples/federation/gateway/package-lock.json
  examples/federation/gateway/yarn.lock
  examples/spring/README.md
  website/README.md
Labels: type: documentation

#612 Upgrade Gradle version and cache based on Java version
  .github/workflows/continuous-integration.yml
  .github/workflows/pr-check.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: type: tool update

#613 Update completable future mapping for coroutines
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
Labels: changes: patch, type: refactor

#614 Update publish docs to use a community action
  .github/workflows/pr-check-docs.yml
  .github/workflows/publish-docs.yml
  website/package-lock.json
  website/package.json
  website/siteConfig.js
Labels: type: documentation

#617 Publish the build directory in the website
  .github/workflows/publish-docs.yml
Labels: type: bug, type: tool update

#618 [docs] Fix publish directory
  .github/workflows/publish-docs.yml
  website/siteConfig.js
Labels: type: tool update

#615 [generator] Fix issue generating nested additional types
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/ConcurrentAdditionalTypesTest.kt
Labels: changes: patch, type: bug

#619 move generation of additional types to an iterative approach
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
Labels: changes: patch, type: refactor

#620 refactor generateAdditionalTypes()
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
Labels: changes: patch, type: refactor

#623 BREAKING CHANGE: Make the KotlinDataFetcherFactoryProvider nullable
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/CustomDataFetcherFactoryProvider.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/SpringDataFetcherFactory.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/KotlinDataFetcherFactoryProvider.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/CustomDataFetcherTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
Labels: changes: major, type: bug

#622 Add additionalTypes to generateSchema
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
Labels: changes: major

#627 Upgrade springboot to fix security issue
  gradle.properties
  graphql-kotlin-schema-generator/build.gradle.kts
Labels: changes: patch, type: dependency changes

#611 Refactor to remove build warnings
  examples/gradle.properties
  gradle.properties
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/FederationConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SubscriptionConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/instrumentation/InstrumentationIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/SubscriptionRoutesConfigurationIT.kt
Labels: changes: patch, type: refactor

#624 Increase Gradle wrapper memory
  examples/gradle.properties
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: type: tool update
