Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2020-03, with the labels that each got.

#633 Polymorphic ignore
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kPropertyExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/filters/propertyFilters.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilder.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/PolymorphicTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
Labels: changes: patch, type: bug

#634 Polymorphic ignore 2.x
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kPropertyExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/filters/propertyFilters.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/PolymorphicTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/filters/PropertyFiltersTest.kt
Labels: changes: patch, type: bug

#636 Custom scalar input
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kTypeExtensions.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KParameterExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/CustomScalarExecutionTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/utils/graphqlUuidType.kt
Labels: changes: patch, type: bug

#639 [docs] Fix the NPM/Github security report issue
  website/package-lock.json
  website/package.json
Labels: type: documentation

#610 [generator] Replace GraphQLContext annotation with interface
  docs/execution/contextual-data.md
  docs/spring-server/spring-graphql-context.md
  docs/writing-schemas/arguments.md
  docs/writing-schemas/nested-queries.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/context/MyGraphQLContext.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ContextualQuery.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/GraphQLContext.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KFunctionExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/GraphQLContextFactory.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/ContextWebFilterTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/GraphQLContextFactoryIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/QueryHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandlerTest.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
Labels: changes: major, type: enhancement

#640 Update dependencies and gradle config
  build.gradle.kts
  examples/build.gradle.kts
  examples/federation/base-app/build.gradle.kts
  examples/federation/extend-app/build.gradle.kts
  examples/settings.gradle.kts
  examples/spring/build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  graphql-kotlin-schema-generator/build.gradle.kts
  graphql-kotlin-spring-server/build.gradle.kts
  settings.gradle.kts
Labels: changes: patch, type: dependency changes

#643 Make SchemaGenerator closeable
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/toFederatedSchema.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/ClassScanner.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/toSchema.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/testSchemaConfig.kt
Labels: changes: patch, type: refactor

#644 Allow for custom subscription return types
  docs/execution/subscriptions.md
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidSubscriptionTypeException.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateSubscription.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateSubscriptionTest.kt
Labels: changes: minor, type: enhancement

#645 Support sealed classes for interfaces
  docs/writing-schemas/interfaces.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/Fruit.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/PolymorphicQuery.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/PolymorphicTests.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateGraphQLTypeKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInterfaceTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
Labels: changes: minor, type: enhancement

#646 Reduce number of class scanners created in tests
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/TypesCache.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/ClassScannerTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLError.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/instrumentation/InstrumentationIT.kt
Labels: changes: patch, type: refactor

#629 Add native subscription support for coroutine Flows
  graphql-kotlin-schema-generator/build.gradle.kts
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategy.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/FlowSubscriptionSchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategyTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
Labels: changes: minor, type: enhancement

#649 Update dependencies to latest versions
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: changes: patch, type: dependency changes

#648 Documentation: Add example using the Spark framework
  CONTRIBUTING.md
  docs/examples.md
  examples/settings.gradle.kts
  examples/spark/README.md
  examples/spark/build.gradle.kts
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/Application.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/GraphQLHandler.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/BookQueryService.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/CourseQueryService.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/HelloQueryService.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/LoginMutationService.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/UniversityQueryService.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/models/Book.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/models/Course.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/models/University.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/models/User.kt
Labels: type: documentation
