Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2020-06, with the labels that each got.

#735 [build] attempt to use default mavenJava publication for plugin
  build.gradle.kts
Labels: type: tool update

#736 [build] update all generated pom.xml with sonatype information
  build.gradle.kts
Labels: type: tool update

#739 [docs] fix client configuration
  docs/client/client-overview.md
Labels: type: documentation

#741 [docs] update interfaces documentation
  docs/writing-schemas/interfaces.md
Labels: type: documentation

#742 Port graphql-java 15 subscription changes to Flow strategy
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategy.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategyTest.kt
Labels: changes: minor, type: enhancement

#743 Replace regex with printer option
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensions.kt
Labels: changes: patch, type: refactor

#744 [docs] fix copy+paste error on downloadSDL task
  docs/plugins/gradle-plugin.md
  plugins/graphql-kotlin-gradle-plugin/README.md
Labels: type: documentation

#748 update graphql kotlin client example to use released version
  examples/client/gradle-client/build.gradle.kts
  examples/client/maven-client/pom.xml
  examples/client/server/build.gradle.kts
Labels: type: documentation

#753 Upgrade federation gateway dependency versions
  examples/federation/gateway/package-lock.json
  examples/federation/gateway/package.json
Labels: type: documentation

#755 [plugin] generate separate file containing type aliases
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGenerateClientTaskIT.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojoTest.kt
  plugins/graphql-kotlin-plugin-core/README.md
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generateClient.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLTestUtils.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt
Labels: changes: patch, type: bug

#754 Simplfy repeated information in the docs
  .github/SECURITY.md
  CONTRIBUTING.md
  README.md
  docs/blogs-and-videos.md
  docs/examples.md
  docs/getting-started.md
  docs/schema-generator/customizing-schemas/advanced-features.md
  docs/schema-generator/customizing-schemas/deprecating-schema.md
  docs/schema-generator/customizing-schemas/directives.md
  docs/schema-generator/customizing-schemas/documenting-fields.md
  docs/schema-generator/customizing-schemas/excluding-fields.md
  docs/schema-generator/customizing-schemas/generator-config.md
  docs/schema-generator/customizing-schemas/renaming-fields.md
  docs/schema-generator/execution/async-models.md
  docs/schema-generator/execution/contextual-data.md
  docs/schema-generator/execution/data-fetching-environment.md
  docs/schema-generator/execution/exceptions.md
  docs/schema-generator/execution/fetching-data.md
  docs/schema-generator/execution/introspection.md
  docs/schema-generator/execution/subscriptions.md
  docs/schema-generator/schema-generator-getting-started.md
  docs/schema-generator/writing-schemas/annotations.md
  docs/schema-generator/writing-schemas/arguments.md
  docs/schema-generator/writing-schemas/enums.md
  docs/schema-generator/writing-schemas/interfaces.md
  docs/schema-generator/writing-schemas/lists.md
  docs/schema-generator/writing-schemas/nested-fields.md
  docs/schema-generator/writing-schemas/nullability.md
  docs/schema-generator/writing-schemas/scalars.md
  docs/schema-generator/writing-schemas/unions.md
  docs/spring-server/spring-overview.md
  docs/writing-schemas/basics.md
  examples/federation/gateway/.npmrc
  examples/federation/gateway/package-lock.json
  website/.gitignore
  website/.npmrc
  website/README.md
  website/package-lock.json
  website/sidebars.json
Labels: type: documentation

#757 [client] fix operation name in the GraphQL request
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt
Labels: changes: patch, type: bug

#759 Clean up docs
  docs/blogs-and-videos.md
  docs/getting-started.md
  docs/schema-generator/customizing-schemas/deprecating-schema.md
  docs/schema-generator/customizing-schemas/documenting-fields.md
  docs/schema-generator/customizing-schemas/excluding-fields.md
  docs/schema-generator/customizing-schemas/renaming-fields.md
  docs/schema-generator/execution/async-models.md
  docs/schema-generator/execution/exceptions.md
  docs/schema-generator/writing-schemas/arguments.md
  docs/schema-generator/writing-schemas/enums.md
  docs/schema-generator/writing-schemas/interfaces.md
  docs/schema-generator/writing-schemas/lists.md
  docs/schema-generator/writing-schemas/nested-arguments.md
  docs/schema-generator/writing-schemas/scalars.md
  docs/schema-generator/writing-schemas/unions.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataAndErrorsQuery.kt
  website/sidebars.json
Labels: type: documentation

#763 [generator] Include java getters for ignore checks
  docs/schema-generator/customizing-schemas/directives.md
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kPropertyExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateDirective.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KCallableExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KPropertyExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
Labels: changes: minor, type: enhancement

#772 Update scalars docs with common issues
  docs/schema-generator/writing-schemas/scalars.md
Labels: type: documentation

#769 [client] expose request builder to allow customization per query execution
  docs/client/client-customization.md
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/resources/templates/Application.mustache
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt
Labels: changes: minor, type: enhancement

#773 [docs] Add server http req/res page
  README.md
  docs/federated/apollo-federation.md
  docs/getting-started.md
  docs/schema-generator/execution/contextual-data.md
  docs/schema-generator/schema-generator-getting-started.md
  docs/spring-server/http-request-response.md
  docs/spring-server/spring-overview.md
  graphql-kotlin-federation/README.md
  graphql-kotlin-schema-generator/README.md
  graphql-kotlin-spring-server/README.md
  website/sidebars.json
Labels: type: documentation

#777 [docs] add 2 blog posts to readme
  README.md
  docs/blogs-and-videos.md
Labels: type: documentation
