Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2020-07, with the labels that each got.

#787 Update the @key directive notes
  docs/federated/federated-directives.md
Labels: type: documentation

#786 [generator] Support subscriptions of Publisher<DataFetcherResult<T>>
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/utils/functionReturnTypes.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/utils/FunctionReturnTypesKtTest.kt
Labels: changes: patch, type: bug

#788 [federation] update @key directive javadoc
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/KeyDirective.kt
Labels: type: documentation

#785 [example] Add example of undefined input vs null
  docs/schema-generator/execution/optional-undefined-arguments.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/mutation/OptionalInputMutation.kt
  website/sidebars.json
Labels: type: documentation

#790 Fix typo
  docs/getting-started.md
Labels: type: documentation

#792 [build] update release build secrets
  .github/workflows/release.yml
Labels: type: tool update

#794 Replace hardcode docs links with page references
  docs/client/client-customization.md
  docs/client/client-overview.md
  docs/spring-server/spring-beans.md
  docs/spring-server/spring-overview.md
Labels: type: documentation

#795 Update codecov action to latest config
  .github/workflows/continuous-integration.yml
  .github/workflows/pr-check.yml
  .github/workflows/release.yml
Labels: type: tool update

#796 Generate xml report for codecov
  build.gradle.kts
  codecov.yml
Labels: type: tool update

#798 Remove codecov reports and links
  .github/workflows/continuous-integration.yml
  CONTRIBUTING.md
  README.md
  build.gradle.kts
  codecov.yml
Labels: type: documentation, type: tool update

#801 Valid polymorphic types in lists as input
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/Application.kt
  examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/LoginMutationService.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/Fruit.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/FieldExtenstionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KParameterExtensionsKtTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
Labels: changes: patch, type: bug

#807 [docs] cut documentation version for 3.x.x releases
  website/pages/en/versions.js
  website/versioned_docs/version-3.4.1/blogs-and-videos.md
  website/versioned_docs/version-3.4.1/client/client-customization.md
  website/versioned_docs/version-3.4.1/client/client-features.md
  website/versioned_docs/version-3.4.1/client/client-overview.md
  website/versioned_docs/version-3.4.1/contributors/release-proc.md
  website/versioned_docs/version-3.4.1/examples.md
  website/versioned_docs/version-3.4.1/federated/apollo-federation.md
  website/versioned_docs/version-3.4.1/federated/federated-directives.md
  website/versioned_docs/version-3.4.1/federated/federated-schemas.md
  website/versioned_docs/version-3.4.1/federated/type-resolution.md
  website/versioned_docs/version-3.4.1/getting-started.md
  website/versioned_docs/version-3.4.1/plugins/gradle-plugin.md
  website/versioned_docs/version-3.4.1/plugins/maven-plugin.md
  website/versioned_docs/version-3.4.1/schema-generator/customizing-schemas/advanced-features.md
  website/versioned_docs/version-3.4.1/schema-generator/customizing-schemas/deprecating-schema.md
  website/versioned_docs/version-3.4.1/schema-generator/customizing-schemas/directives.md
  website/versioned_docs/version-3.4.1/schema-generator/customizing-schemas/documenting-fields.md
  website/versioned_docs/version-3.4.1/schema-generator/customizing-schemas/excluding-fields.md
  website/versioned_docs/version-3.4.1/schema-generator/customizing-schemas/generator-config.md
  website/versioned_docs/version-3.4.1/schema-generator/customizing-schemas/renaming-fields.md
  website/versioned_docs/version-3.4.1/schema-generator/execution/async-models.md
  website/versioned_docs/version-3.4.1/schema-generator/execution/contextual-data.md
  website/versioned_docs/version-3.4.1/schema-generator/execution/data-fetching-environment.md
  website/versioned_docs/version-3.4.1/schema-generator/execution/exceptions.md
  website/versioned_docs/version-3.4.1/schema-generator/execution/fetching-data.md
  website/versioned_docs/version-3.4.1/schema-generator/execution/introspection.md
  website/versioned_docs/version-3.4.1/schema-generator/execution/optional-undefined-arguments.md
  website/versioned_docs/version-3.4.1/schema-generator/execution/subscriptions.md
  website/versioned_docs/version-3.4.1/schema-generator/schema-generator-getting-started.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/annotations.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/arguments.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/enums.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/interfaces.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/lists.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/nested-arguments.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/nullability.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/scalars.md
  website/versioned_docs/version-3.4.1/schema-generator/writing-schemas/unions.md
  website/versioned_docs/version-3.4.1/spring-server/http-request-response.md
  website/versioned_docs/version-3.4.1/spring-server/spring-beans.md
  website/versioned_docs/version-3.4.1/spring-server/spring-graphql-context.md
  website/versioned_docs/version-3.4.1/spring-server/spring-overview.md
  website/versioned_docs/version-3.4.1/spring-server/spring-properties.md
  website/versioned_docs/version-3.4.1/spring-server/subscriptions.md
  website/versioned_sidebars/version-3.4.1-sidebars.json
  website/versions.json
Labels: type: documentation

#809 bump up current doc version to 3.4.2
  website/versioned_docs/version-3.4.2/blogs-and-videos.md
  website/versioned_docs/version-3.4.2/client/client-customization.md
  website/versioned_docs/version-3.4.2/client/client-features.md
  website/versioned_docs/version-3.4.2/client/client-overview.md
  website/versioned_docs/version-3.4.2/contributors/release-proc.md
  website/versioned_docs/version-3.4.2/examples.md
  website/versioned_docs/version-3.4.2/federated/apollo-federation.md
  website/versioned_docs/version-3.4.2/federated/federated-directives.md
  website/versioned_docs/version-3.4.2/federated/federated-schemas.md
  website/versioned_docs/version-3.4.2/federated/type-resolution.md
  website/versioned_docs/version-3.4.2/getting-started.md
  website/versioned_docs/version-3.4.2/plugins/gradle-plugin.md
  website/versioned_docs/version-3.4.2/plugins/maven-plugin.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/advanced-features.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/deprecating-schema.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/directives.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/documenting-fields.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/excluding-fields.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/generator-config.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/renaming-fields.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/async-models.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/contextual-data.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/data-fetching-environment.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/exceptions.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/fetching-data.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/introspection.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/optional-undefined-arguments.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/subscriptions.md
  website/versioned_docs/version-3.4.2/schema-generator/schema-generator-getting-started.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/annotations.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/arguments.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/enums.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/interfaces.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/lists.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/nested-arguments.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/nullability.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/scalars.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/unions.md
  website/versioned_docs/version-3.4.2/spring-server/http-request-response.md
  website/versioned_docs/version-3.4.2/spring-server/spring-beans.md
  website/versioned_docs/version-3.4.2/spring-server/spring-graphql-context.md
  website/versioned_docs/version-3.4.2/spring-server/spring-overview.md
  website/versioned_docs/version-3.4.2/spring-server/spring-properties.md
  website/versioned_docs/version-3.4.2/spring-server/subscriptions.md
  website/versioned_sidebars/version-3.4.1-sidebars.json
  website/versioned_sidebars/version-3.4.2-sidebars.json
  website/versions.json
Labels: type: documentation

#814 fix documentation
  website/versioned_docs/version-3.4.2/client/client-customization.md
  website/versioned_docs/version-3.4.2/client/client-features.md
  website/versioned_docs/version-3.4.2/client/client-overview.md
  website/versioned_docs/version-3.4.2/contributors/release-proc.md
  website/versioned_docs/version-3.4.2/federated/apollo-federation.md
  website/versioned_docs/version-3.4.2/federated/federated-directives.md
  website/versioned_docs/version-3.4.2/federated/federated-schemas.md
  website/versioned_docs/version-3.4.2/federated/type-resolution.md
  website/versioned_docs/version-3.4.2/plugins/gradle-plugin.md
  website/versioned_docs/version-3.4.2/plugins/maven-plugin.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/advanced-features.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/deprecating-schema.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/directives.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/documenting-fields.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/excluding-fields.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/generator-config.md
  website/versioned_docs/version-3.4.2/schema-generator/customizing-schemas/renaming-fields.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/async-models.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/contextual-data.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/data-fetching-environment.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/exceptions.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/fetching-data.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/introspection.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/optional-undefined-arguments.md
  website/versioned_docs/version-3.4.2/schema-generator/execution/subscriptions.md
  website/versioned_docs/version-3.4.2/schema-generator/schema-generator-getting-started.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/annotations.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/arguments.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/enums.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/interfaces.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/lists.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/nested-arguments.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/nullability.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/scalars.md
  website/versioned_docs/version-3.4.2/schema-generator/writing-schemas/unions.md
  website/versioned_docs/version-3.4.2/spring-server/http-request-response.md
  website/versioned_docs/version-3.4.2/spring-server/spring-beans.md
  website/versioned_docs/version-3.4.2/spring-server/spring-graphql-context.md
  website/versioned_docs/version-3.4.2/spring-server/spring-overview.md
  website/versioned_docs/version-3.4.2/spring-server/spring-properties.md
  website/versioned_docs/version-3.4.2/spring-server/subscriptions.md
Labels: type: documentation

#810 [client] set default null value for input arguments
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLInputObjectTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateVariableTypeSpec.kt
  plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt
Labels: changes: patch

#811 [client] open up GraphQL client
  docs/client/client-customization.md
  graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
Labels: changes: minor, type: enhancement

#813 [server] spring aware data fetcher
  docs/schema-generator/writing-schemas/arguments.md
  docs/schema-generator/writing-schemas/nested-arguments.md
  docs/spring-server/spring-beans.md
  docs/spring-server/spring-overview.md
  docs/spring-server/spring-schema.md
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/dataloaders/DataLoaderConfiguration.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/CustomDataFetcherFactoryProvider.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/CustomFunctionDataFetcher.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/DataLoaderQueryModel.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataLoaderQuery.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/SpringAwareQuery.kt
  examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/WidgetQuery.kt
  examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/query/SpringAwareQueryIT.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
  graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SpringDataFetcher.kt
  graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SpringDataFetcherIT.kt
  website/sidebars.json
Labels: changes: minor, type: enhancement

#817 [generator] Update additional types to work with input types
  detekt.yml
  graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
  graphql-kotlin-schema-generator/build.gradle.kts
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/AdditionalType.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInterfaceTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/scalars/IDTest.kt
Labels: changes: minor, type: enhancement

#821 [generator] Do not add interfaces for input additional types
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
  graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
  graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
Labels: changes: patch, type: bug
