Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2021-07, with the labels that each got.

#1207 Fix invalid link in documentation
  website/docs/server/spring-server/spring-schema.md
Labels: type: documentation

#1208 Fix the scalar converter link
  website/docs/plugins/gradle-plugin-usage.mdx
Labels: type: documentation

#1211 [docs] fix sidebars
  website/docusaurus.config.js
  website/sidebars.js
  website/sidebars.json
  website/versioned_sidebars/version-4.x.x-sidebars.json
Labels: type: documentation

#1212 Add local schema file support to Gradle plugin extension
  plugins/graphql-kotlin-gradle-plugin/README.md
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
  website/docs/plugins/gradle-plugin-tasks.mdx
Labels: changes: minor, module: plugin

#1217 getValuesFromDataLoader helper function
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/dataFetchingEnvironmentExtensions.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/DataFetchingEnvironmentExtensionsKtTest.kt
Labels: changes: minor, module: server

#1228 Update dependecy versions
  clients/graphql-kotlin-client-serialization/build.gradle.kts
  gradle.properties
Labels: changes: patch, type: dependency changes

#1215 [plugin] simplify client handling of custom scalars
  examples/client/gradle-client/src/main/kotlin/com/expediagroup/graphql/examples/client/gradle/Application.kt
  examples/client/gradle-client/src/main/resources/ExampleQuery.graphql
  examples/client/maven-client/src/main/resources/ExampleQuery.graphql
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/SimpleQueries.kt
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/model/ScalarWrapper.kt
  examples/client/src/integration/wiremock/__files/schema.graphql
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGeneratorConfig.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGeneratorContext.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLCustomScalarConverters.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLCustomScalarTypeSpec.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generatePropertySpecs.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateTypeName.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/CustomScalarQuery.graphql
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/CustomScalarQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/customscalarquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/scalars/AnyToUUIDConverter.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/scalars/UUID.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/scalars/UUIDToAnyConverter.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalars/CustomScalarQuery.graphql
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalars/CustomScalarQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalars/customscalarquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalars/scalars/UUIDSerializer.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/firstquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/scalars/UUIDSerializer.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/secondquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/resources/testSchema.graphql
  plugins/graphql-kotlin-gradle-plugin/src/test/resources/templates/Application.mustache
  plugins/graphql-kotlin-maven-plugin/src/integration/basic-setup/src/main/resources/ExampleQuery.graphql
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup-jackson/src/main/resources/ExampleQuery.graphql
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup-jackson/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup-kotlinx/src/main/resources/ExampleQuery.graphql
  plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup-kotlinx/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/introspectionResult.json
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/response.json
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/testSchema.graphql
  website/docs/client/client-customization.mdx
Labels: changes: major, module: plugin

#1229 Update dokka to 1.5
  gradle.properties
Labels: changes: patch, type: bug

#1230 Fix deprecations and compile warnings
  clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/types/serializers/AnyKSerializerTest.kt
  clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/types/serializers/GraphQLErrorPathSerializerTest.kt
  clients/graphql-kotlin-ktor-client/src/test/kotlin/com/expediagroup/graphql/client/ktor/GraphQLKtorClientTest.kt
  clients/graphql-kotlin-spring-client/src/test/kotlin/com/expediagroup/graphql/client/spring/GraphQLWebClientTest.kt
  examples/gradle/wrapper/gradle-wrapper.properties
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/directives/CustomDirectiveWiringFactory.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/directives/LowercaseSchemaDirectiveWiring.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/directives/StringEvalSchemaDirectiveWiring.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/hooks/CustomSchemaGeneratorHooks.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/ScalarQuery.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateDirective.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateUnion.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/KotlinDirectiveWiringFactoryTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/AnnotationExtensionsTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KPropertyExtensionsKtTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateFunctionTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GeneratePropertyTest.kt
  gradle/wrapper/gradle-wrapper.properties
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generateClient.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLEnumTypeSpec.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateInterfaceTypeSpec.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateTypeName.kt
  plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/DownloadSchemaTest.kt
  plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/IntrospectSchemaTest.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/actions/GenerateClientAction.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/parameters/GenerateClientParameters.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt
  plugins/graphql-kotlin-maven-plugin/pom.xml
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLRoutesConfiguration.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandlerTest.kt
  website/docs/client/client-customization.mdx
  website/docs/client/client-features.mdx
  website/docs/client/client-overview.mdx
  website/docs/client/client-serialization.mdx
  website/docs/getting-started.mdx
  website/docs/plugins/gradle-plugin-tasks.mdx
  website/docs/plugins/gradle-plugin-usage.mdx
  website/docs/plugins/hooks-provider.mdx
  website/docs/schema-generator/federation/apollo-federation.mdx
  website/docs/schema-generator/schema-generator-getting-started.mdx
  website/docs/server/spring-server/spring-overview.mdx
  website/src/theme/DocVersionSuggestions/index.js
  website/static/img/kotlin-logo.svg
  website/versioned_docs/version-4.x.x/client/client-customization.mdx
  website/versioned_docs/version-4.x.x/client/client-features.mdx
  website/versioned_docs/version-4.x.x/client/client-overview.mdx
  website/versioned_docs/version-4.x.x/client/client-serialization.mdx
  website/versioned_docs/version-4.x.x/getting-started.mdx
  website/versioned_docs/version-4.x.x/plugins/gradle-plugin-tasks.mdx
  website/versioned_docs/version-4.x.x/plugins/gradle-plugin-usage.mdx
  website/versioned_docs/version-4.x.x/plugins/hooks-provider.mdx
  website/versioned_docs/version-4.x.x/schema-generator/federation/apollo-federation.mdx
  website/versioned_docs/version-4.x.x/schema-generator/schema-generator-getting-started.mdx
  website/versioned_docs/version-4.x.x/server/spring-server/spring-overview.mdx
Labels: changes: patch, type: dependency changes

#1231 [plugin] support android compile targets
  build.gradle.kts
  gradle.properties
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/schema.graphql
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/src/main/AndroidManifest.xml
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/src/main/resources/ExampleQuery.graphql
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/gradle.properties
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/settings.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/ProjectExtensions.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAndroidIT.kt
Labels: changes: patch, module: plugin
