Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2021-02, with the labels that each got.

#1035 Update graphql-java 16.2
  gradle.properties
Labels: changes: patch, type: dependency changes

#1031 Simplify setup of dataloaders in spring server
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/dataloaders/DataLoaderConfiguration.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/model/DataLoaderQueryModel.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/DataLoaderQuery.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/exception/MissingDataLoaderException.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/DataLoaderRegistryFactory.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/KotlinDataLoader.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/dataFetchingEnvironmentExtensions.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/execution/DefaultDataLoaderRegistryFactoryTest.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/DataFetchingEnvironmentExtensionsKtTest.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLExecutionConfiguration.kt
Labels: changes: minor, module: server, type: enhancement

#1041 Delete older alpha docs
  website/package-lock.json
  website/versioned_docs/version-4.0.0-alpha.10/schema-generator/execution/optional-undefined-arguments.md
  website/versioned_docs/version-4.0.0-alpha.10/schema-generator/writing-schemas/arguments.md
  website/versioned_docs/version-4.0.0-alpha.11/examples.md
  website/versioned_docs/version-4.0.0-alpha.11/getting-started.md
  website/versioned_docs/version-4.0.0-alpha.11/plugins/gradle-plugin-examples.md
  website/versioned_docs/version-4.0.0-alpha.11/plugins/gradle-plugin.md
  website/versioned_docs/version-4.0.0-alpha.11/plugins/hooks-provider.md
  website/versioned_docs/version-4.0.0-alpha.11/plugins/maven-plugin-examples.md
  website/versioned_docs/version-4.0.0-alpha.11/plugins/maven-plugin.md
  website/versioned_docs/version-4.0.0-alpha.11/schema-generator/execution/contextual-data.md
  website/versioned_docs/version-4.0.0-alpha.11/schema-generator/writing-schemas/nested-arguments.md
  website/versioned_docs/version-4.0.0-alpha.11/server/data-loader-registry-factory.md
  website/versioned_docs/version-4.0.0-alpha.11/server/graphql-context-factory.md
  website/versioned_docs/version-4.0.0-alpha.11/server/graphql-request-handler.md
  website/versioned_docs/version-4.0.0-alpha.11/server/graphql-request-parser.md
  website/versioned_docs/version-4.0.0-alpha.11/server/graphql-server.md
  website/versioned_docs/version-4.0.0-alpha.11/server/server-subscriptions.md
  website/versioned_docs/version-4.0.0-alpha.11/server/spring-server/spring-beans.md
  website/versioned_docs/version-4.0.0-alpha.11/server/spring-server/spring-graphql-context.md
  website/versioned_docs/version-4.0.0-alpha.11/server/spring-server/spring-overview.md
  website/versioned_docs/version-4.0.0-alpha.11/server/spring-server/spring-properties.md
  website/versioned_docs/version-4.0.0-alpha.11/server/spring-server/spring-schema.md
  website/versioned_docs/version-4.0.0-alpha.11/server/spring-server/spring-subscriptions.md
  website/versioned_docs/version-4.0.0-alpha.2/client/client-customization.md
  website/versioned_docs/version-4.0.0-alpha.2/client/client-overview.md
  website/versioned_docs/version-4.0.0-alpha.2/federated/apollo-federation.md
  website/versioned_docs/version-4.0.0-alpha.2/federated/federated-directives.md
  website/versioned_docs/version-4.0.0-alpha.2/federated/federated-schemas.md
  website/versioned_docs/version-4.0.0-alpha.2/federated/type-resolution.md
  website/versioned_docs/version-4.0.0-alpha.2/plugins/gradle-plugin.md
  website/versioned_docs/version-4.0.0-alpha.2/plugins/maven-plugin.md
  website/versioned_docs/version-4.0.0-alpha.2/schema-generator/customizing-schemas/renaming-fields.md
  website/versioned_docs/version-4.0.0-alpha.2/schema-generator/execution/optional-undefined-arguments.md
  website/versioned_docs/version-4.0.0-alpha.2/spring-server/spring-beans.md
  website/versioned_docs/version-4.0.0-alpha.4/graphql-java-comparison.md
  website/versioned_docs/version-4.0.0-alpha.6/plugins/gradle-plugin.md
  website/versioned_docs/version-4.0.0-alpha.7/blogs-and-videos.md
  website/versioned_docs/version-4.0.0-alpha.7/client/client-overview.md
  website/versioned_docs/version-4.0.0-alpha.7/plugins/gradle-plugin.md
  website/versioned_docs/version-4.0.0-alpha.7/plugins/maven-plugin.md
  website/versioned_docs/version-4.0.0-alpha.8/plugins/gradle-plugin.md
  website/versioned_docs/version-4.0.0-alpha.8/plugins/maven-plugin.md
  website/versioned_docs/version-4.0.0-alpha.8/schema-generator/execution/fetching-data.md
  website/versioned_docs/version-4.0.0-alpha.9/examples.md
  website/versioned_docs/version-4.0.0-alpha.9/schema-generator/customizing-schemas/advanced-features.md
  website/versioned_docs/version-4.0.0-alpha.9/schema-generator/execution/subscriptions.md
  website/versioned_docs/version-4.0.0-alpha.9/spring-server/subscriptions.md
  website/versioned_sidebars/version-4.0.0-alpha.11-sidebars.json
  website/versioned_sidebars/version-4.0.0-alpha.4-sidebars.json
  website/versions.json
Labels: type: documentation

#1044 [docs] updating invalid refresh link in index.html
  website/static/index.html
Labels: type: bug, type: documentation

#1055 Update website publish
  .github/workflows/continuous-integration.yml
  .github/workflows/pr-check-docs.yml
  .github/workflows/pr-check.yml
  .github/workflows/publish-latest-docs.yml
  .github/workflows/release-docs.yml
  website/package.json
  website/static/index.html
Labels: type: bug, type: documentation

#1056 Update index redirect
  website/static/index.html
Labels: type: documentation

#1057 Add docs back to url
  website/docs/schema-generator/customizing-schemas/advanced-features.md
  website/docusaurus.config.js
  website/static/index.html
  website/versioned_docs/version-3.x.x/schema-generator/customizing-schemas/advanced-features.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/advanced-features.md
Labels: type: documentation

#1058 Add trailing slash
  website/static/index.html
Labels: type: documentation

#1059 Move federation docs under generator folder
  generator/graphql-kotlin-federation/README.md
  website/docs/getting-started.mdx
  website/docs/plugins/gradle-plugin-tasks.mdx
  website/docs/plugins/gradle-plugin-usage.mdx
  website/docs/plugins/maven-plugin-goals.md
  website/docs/plugins/maven-plugin-usage.md
  website/docs/schema-generator/customizing-schemas/advanced-features.md
  website/docs/schema-generator/federation/apollo-federation.md
  website/docs/schema-generator/federation/federated-directives.md
  website/docs/schema-generator/federation/federated-schemas.md
  website/docs/schema-generator/federation/type-resolution.md
  website/docs/server/spring-server/spring-beans.md
  website/sidebars.json
  website/versioned_docs/version-4.x.x/plugins/maven-plugin.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/renaming-fields.md
Labels: type: documentation

#1053 Generate context with suspend and nullable in subscriptions
  examples/build.gradle.kts
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/KtorGraphQLContextFactory.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/context/MyGraphQLContext.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/context/MyGraphQLContextFactory.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/execution/MySubscriptionHooks.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/subscriptions/SimpleSubscription.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/GraphQLContext.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLContextFactory.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/requestExtensions.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/RequestExtensionsKtTest.kt
  servers/graphql-kotlin-spring-server/build.gradle.kts
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/SubscriptionAutoConfiguration.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLContextFactory.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionHooks.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandler.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionSessionState.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringSubscriptionGraphQLContextFactory.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/context/GraphQLContextFactoryIT.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandlerTest.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SubscriptionWebSocketHandlerIT.kt
  website/docs/schema-generator/execution/contextual-data.md
  website/docs/server/graphql-context-factory.md
  website/docs/server/graphql-request-handler.md
  website/docs/server/graphql-request-parser.md
  website/docusaurus.config.js
Labels: changes: major, module: server

#1061 fix release-docs workflow
  .github/workflows/release-docs.yml
Labels: type: tool update

#1060 Delete versioned 4.x.x docs for renamed current docs
  .github/workflows/release-docs.yml
  website/docusaurus.config.js
  website/versioned_docs/version-4.x.x/assets/spring-initializer.png
  website/versioned_docs/version-4.x.x/blogs-and-videos.md
  website/versioned_docs/version-4.x.x/client/client-customization.md
  website/versioned_docs/version-4.x.x/client/client-features.md
  website/versioned_docs/version-4.x.x/client/client-overview.mdx
  website/versioned_docs/version-4.x.x/contributors/release-proc.md
  website/versioned_docs/version-4.x.x/examples.md
  website/versioned_docs/version-4.x.x/federated/apollo-federation.md
  website/versioned_docs/version-4.x.x/federated/federated-directives.md
  website/versioned_docs/version-4.x.x/federated/federated-schemas.md
  website/versioned_docs/version-4.x.x/federated/type-resolution.md
  website/versioned_docs/version-4.x.x/getting-started.mdx
  website/versioned_docs/version-4.x.x/graphql-java-comparison.md
  website/versioned_docs/version-4.x.x/plugins/gradle-plugin-tasks.mdx
  website/versioned_docs/version-4.x.x/plugins/gradle-plugin-usage.mdx
  website/versioned_docs/version-4.x.x/plugins/gradle-plugin.md
  website/versioned_docs/version-4.x.x/plugins/hooks-provider.mdx
  website/versioned_docs/version-4.x.x/plugins/maven-plugin-goals.md
  website/versioned_docs/version-4.x.x/plugins/maven-plugin-usage.md
  website/versioned_docs/version-4.x.x/plugins/maven-plugin.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/advanced-features.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/deprecating-schema.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/directives.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/documenting-fields.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/excluding-fields.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/generator-config.md
  website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/renaming-fields.md
  website/versioned_docs/version-4.x.x/schema-generator/execution/async-models.md
  website/versioned_docs/version-4.x.x/schema-generator/execution/contextual-data.md
  website/versioned_docs/version-4.x.x/schema-generator/execution/data-fetching-environment.md
  website/versioned_docs/version-4.x.x/schema-generator/execution/exceptions.md
  website/versioned_docs/version-4.x.x/schema-generator/execution/fetching-data.md
  website/versioned_docs/version-4.x.x/schema-generator/execution/introspection.md
  website/versioned_docs/version-4.x.x/schema-generator/execution/optional-undefined-arguments.md
  website/versioned_docs/version-4.x.x/schema-generator/execution/subscriptions.md
  website/versioned_docs/version-4.x.x/schema-generator/schema-generator-getting-started.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/annotations.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/arguments.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/enums.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/interfaces.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/lists.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/nested-arguments.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/nullability.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/scalars.md
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/unions.md
  website/versioned_docs/version-4.x.x/server/data-loaders.md
  website/versioned_docs/version-4.x.x/server/graphql-context-factory.md
  website/versioned_docs/version-4.x.x/server/graphql-request-handler.md
  website/versioned_docs/version-4.x.x/server/graphql-request-parser.md
  website/versioned_docs/version-4.x.x/server/graphql-server.md
  website/versioned_docs/version-4.x.x/server/server-subscriptions.md
  website/versioned_docs/version-4.x.x/server/spring-server/spring-beans.md
  website/versioned_docs/version-4.x.x/server/spring-server/spring-graphql-context.md
  website/versioned_docs/version-4.x.x/server/spring-server/spring-overview.mdx
  website/versioned_docs/version-4.x.x/server/spring-server/spring-properties.md
  website/versioned_docs/version-4.x.x/server/spring-server/spring-schema.md
  website/versioned_docs/version-4.x.x/server/spring-server/spring-subscriptions.md
  website/versions.json
Labels: type: documentation
