Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2021-11, with the labels that each got.

#1295 Add example which requires an external array
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/federation/base/schema/Widget.kt
  examples/federation/base-app/src/test/kotlin/com/expediagroup/graphql/examples/federation/base/schema/WidgetTest.kt
  examples/federation/extend-app/src/main/kotlin/com/expediagroup/graphql/examples/federation/extend/schema/Widget.kt
  examples/federation/extend-app/src/main/kotlin/com/expediagroup/graphql/examples/federation/extend/schema/WidgetResolver.kt
  examples/federation/gateway/package-lock.json
  examples/federation/gateway/package.json
Labels: type: documentation

#1299 Upgrade classgraph to 4.2.131
  gradle.properties
Labels: changes: patch, type: dependency changes, module: generator

#1284 [client] support optional scalar input
  plugins/client/graphql-kotlin-client-generator/build.gradle.kts
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGeneratorContext.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLCustomScalarTypeAlias.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLInputObjectTypeSpec.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateJacksonOptionalInputScalarSerializer.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generatePropertySpecs.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateVariableTypeSpec.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalar_input/CustomScalarInputQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalar_input/inputs/ScalarWrapperInput.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalar_input/scalars/OptionalScalarInputSerializer.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalar_input/CustomScalarInputQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalar_input/inputs/ScalarWrapperInput.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/FirstQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/SecondQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/inputs/ComplexArgumentInput.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/variables/KotlinXInputQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/variables/inputs/SimpleArgumentInput.kt
  plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/GenerateKotlinxClientIT.kt
  plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLTestUtils.kt
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars/src/main/kotlin/com/expediagroup/scalars/ScalarWrapper.kt
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars/src/test/kotlin/com/expediagroup/scalars/CustomScalarApplicationTests.kt
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars/src/test/resources/CustomScalarsQuery.graphql
  website/docs/client/client-customization.mdx
  website/docs/client/client-features.mdx
Labels: changes: patch, module: client

#1302 Update graphql-request-parser.md
  website/docs/server/graphql-request-parser.md
Labels: type: documentation
