Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2021-08, with the labels that each got.

#1235 [plugin] update generateClientTasks to correctly monitor inputs
  plugins/graphql-kotlin-gradle-plugin/README.md
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTask.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateTestClientTask.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAndroidIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTaskIT.kt
  website/docs/plugins/gradle-plugin-tasks.mdx
  website/docs/plugins/gradle-plugin-usage.mdx
Labels: changes: major, module: plugin

#1238 Backport Union changes to 4xx docs
  website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/unions.md
Labels: type: documentation

#1236 [dependency] update to GraphQL Java 17
  examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/Application.kt
  examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/federation/base/hooks/CustomFederationSchemaGeneratorHooks.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/directives/SpecificValueOnlySchemaDirectiveWiring.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/directives/StringEvalSchemaDirectiveWiring.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/hooks/CustomSchemaGeneratorHooks.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/types/_Any.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/types/_FieldSet.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateDirective.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/federationDirectives.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/types/AnyTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/ValidateDirectiveKtTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/DirectiveTests.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/KotlinDirectiveWiringFactoryTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLSchemaExtensionsTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateDirectiveTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateFunctionTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateObjectTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GeneratePropertyTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/utils/graphqlUuidType.kt
  gradle.properties
  plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/IntrospectSchemaTest.kt
  plugins/client/graphql-kotlin-client-generator/src/test/resources/introspectionResult.json
  plugins/client/graphql-kotlin-client-generator/src/test/resources/testSchema.graphql
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/resources/mocks/CustomFederatedHooks.txt
  plugins/graphql-kotlin-gradle-plugin/src/test/resources/mocks/IntrospectionResult.json
  plugins/graphql-kotlin-gradle-plugin/src/test/resources/mocks/schema.graphql
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/main/kotlin/com/example/hooks/CustomFederatedHooks.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/introspectionResult.json
  plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/testSchema.graphql
  plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
  plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/test/hooks/CustomFederatedHooks.kt
  plugins/schema/graphql-kotlin-sdl-generator/src/test/kotlin/com/expediagroup/graphql/plugin/schema/GenerateSDLTest.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/DataFetcherIT.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt
Labels: changes: patch, type: dependency changes, module: generator

#1242 [client] verify selection sets specify all required inputs
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/exceptions/MissingArgumentException.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generatePropertySpecs.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/invalid/missing_argument/MissingArgumentQuery.graphql
  plugins/client/graphql-kotlin-client-generator/src/test/data/invalid/missing_argument/exception.txt
Labels: changes: patch, module: client

#1244 junit fix - bump up the query timeout
  clients/graphql-kotlin-spring-client/src/test/kotlin/com/expediagroup/graphql/client/spring/GraphQLWebClientTest.kt
Labels: changes: patch

#1247 Expose CoroutineContext as constructor argument
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt
Labels: type: enhancement, changes: minor

#1254 [build] update to build on Java 11 with targetJVM 1.8
  .github/workflows/continuous-integration.yml
  .github/workflows/pr-check.yml
  .github/workflows/release-code.yml
  build.gradle.kts
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KTypeExtensionsKtTest.kt
Labels: type: tool update
