Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2021-03, with the labels that each got.

#1072 Add documentation for subscription hooks
  website/docs/server/spring-server/spring-subscriptions.md
Labels: type: documentation

#1078 [docs] update serialization docs to use introspection
  website/docs/client/client-serialization.mdx
Labels: type: documentation

#1085 Add data loader registry to subscription execution
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/SubscriptionAutoConfiguration.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLSubscriptionHandlerTest.kt
Labels: changes: patch, module: server

#1083 Do not wrap exceptions twice
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/exceptions/CustomDataFetcherExceptionHandler.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/DataAndErrorsQuery.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/subscriptions/SimpleSubscription.kt
  examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/server/spring/query/CustomDirectiveQueryIT.kt
  examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/server/spring/query/DataAndErrorsQueryIT.kt
  examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/server/spring/query/ValidatedQueryIT.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/exception/KotlinGraphQLError.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLRequestHandler.kt
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/responseExtensions.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/exception/KotlinGraphQLErrorTest.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/execution/GraphQLRequestHandlerTest.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/ResponseExtensionsKtTest.kt
  servers/graphql-kotlin-spring-server/build.gradle.kts
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLExecutionConfiguration.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/exception/KotlinDataFetcherExceptionHandler.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/exception/KotlinDataFetcherExceptionHandlerTest.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLSubscriptionHandlerTest.kt
Labels: changes: major, module: generator, module: server

#1086 Update the docs on the exception handler
  website/docs/server/spring-server/spring-beans.md
Labels: type: documentation

#1089 [build] update to use latest dependencies
  clients/graphql-kotlin-client-jackson/src/test/kotlin/com/expediagroup/graphql/client/jackson/data/polymorphicquery/BasicInterface.kt
  gradle.properties
Labels: changes: patch, type: dependency changes

#1090 [build] update to latest dokka
  build.gradle.kts
  gradle.properties
Labels: type: tool update

#1091 [build] update publish plugin
  .github/workflows/release-code.yml
  build.gradle.kts
  gradle.properties
  settings.gradle.kts
Labels: type: tool update

#1093 [build] update release build to automatically release to nexus
  .github/workflows/release-code.yml
Labels: type: tool update

#1099 Add docs on the spring specific context requirements
  website/docs/server/graphql-context-factory.md
  website/docs/server/spring-server/spring-graphql-context.md
Labels: type: documentation

#1102 Add unit tests for optional input wrappers
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/OptionalInputQuery.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateArgumentTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/OptionalInputTest.kt
Labels: changes: patch, module: examples, module: generator, type: refactor

#1101 Fix playground route logic
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/PlaygroundRouteConfiguration.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandler.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/subscriptionUtils.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SubscriptionUtilsKtTest.kt
Labels: changes: patch, module: server, type: bug

#1103 Support OptionalInput of any list or array
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/exceptions/InvalidWrappedTypeException.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kParameterExtensions.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kTypeExtensions.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcherTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KParameterExtensionsKtTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KTypeExtensionsKtTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/OptionalInputTest.kt
Labels: changes: patch, module: generator, type: bug

#1107 [client] fix unknown enum import
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLObjectTypeSpec.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/enums/EnumQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/enums/EnumQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/FirstQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/SecondQuery.kt
Labels: changes: patch, module: client, type: bug
