Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2022-01, with the labels that each got.

#1342 [docs] fix readme links for client generator
  plugins/client/graphql-kotlin-client-generator/README.md
Labels: type: documentation

#1338 Updated schema generator to support return DataFetcherResult of list of DataFetcherResult
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/utils/functionReturnTypes.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/utils/FunctionReturnTypesKtTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/DataFetcherResultListTest.kt
Labels: changes: patch, module: generator

#1341 [client] support @include and @skip directives
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLObjectTypeSpec.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generatePropertySpecs.kt
  plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateTypeName.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/generator/include_skip_directives/IncludeSkipDirectivesQuery.graphql
  plugins/client/graphql-kotlin-client-generator/src/test/data/generator/include_skip_directives/IncludeSkipDirectivesQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/generator/include_skip_directives/enums/CustomEnum.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/generator/include_skip_directives/includeskipdirectivesquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/generator/input_lists/InputListQuery.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/generator/scalar_typealias/scalaraliasquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/customscalarquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/object/complexobjectquery/ComplexObject.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/firstquery/ComplexObject.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/firstquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/secondquery/ScalarWrapper.kt
  plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/object/complexobjectquery/ComplexObject.kt
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/settings.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/main/kotlin/com/expediagroup/directives/Application.kt
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/main/kotlin/com/expediagroup/directives/SimpleQuery.kt
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/main/resources/application.yml
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/test/kotlin/com/expediagroup/directives/ApplicationTest.kt
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/test/resources/IncludeSkipQuery.graphql
Labels: changes: patch, module: client, module: plugin

#1343 Release drafter now supports putting "other changes" in a category
  .github/release-drafter.yml
Labels: type: tool update

#1345 Fix broken link
  website/docs/server/spring-server/spring-overview.mdx
Labels: type: documentation

#1351 examples/ktor-server: expose GraphQL Schema at /sdl
  examples/server/ktor-server/README.md
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/GraphQLModule.kt
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/ktorGraphQLSchema.kt
Labels: module: examples

#1354 [build] update to Gradle 7.3.3
  examples/gradle/wrapper/gradle-wrapper.properties
  examples/gradlew
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: type: tool update
