Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2023-01, with the labels that each got.

#1626 feat: add explorer and exporter plugins
  servers/graphql-kotlin-spring-server/src/main/resources/graphql-graphiql.html
Labels: changes: patch

#1627 [build] update to kotlin 1.7.21
  gradle.properties
  plugins/client/graphql-kotlin-client-generator/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars_jackson/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars_kotlinx/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/jacoco/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/polymorphic_types_jackson/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/polymorphic_types_kotlinx/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGenerateClientIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
  plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAndroidIT.kt
Labels: type: dependency changes

#1629 docs: cleanup fed example docs
  examples/federation/README.md
Labels: type: documentation

#1630 migrate build to version catalog
  build.gradle.kts
  clients/graphql-kotlin-client-jackson/build.gradle.kts
  clients/graphql-kotlin-client-serialization/build.gradle.kts
  clients/graphql-kotlin-client/build.gradle.kts
  clients/graphql-kotlin-ktor-client/build.gradle.kts
  clients/graphql-kotlin-spring-client/build.gradle.kts
  examples/build.gradle.kts
  examples/client/build.gradle.kts
  examples/client/gradle-client/build.gradle.kts
  examples/client/maven-client/build.gradle.kts
  examples/federation/products-subgraph/build.gradle.kts
  examples/federation/reviews-subgraph/build.gradle.kts
  examples/server/ktor-server/build.gradle.kts
  examples/server/ktor-server/gradle.properties
  examples/server/spring-server/build.gradle.kts
  examples/settings.gradle.kts
  executions/graphql-kotlin-automatic-persisted-queries/build.gradle.kts
  executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
  executions/graphql-kotlin-dataloader/build.gradle.kts
  generator/graphql-kotlin-federation/build.gradle.kts
  generator/graphql-kotlin-schema-generator/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  plugins/client/graphql-kotlin-client-generator/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-maven-plugin/build.gradle.kts
  plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts
  servers/graphql-kotlin-server/build.gradle.kts
  servers/graphql-kotlin-spring-server/build.gradle.kts
Labels: type: tool update

#1632 fix: use proper path to fed compatibility jar
  integration/federation-compatibility/Dockerfile
Labels: type: tool update

#1634 chore: update federation-jvm version to 2.2.0
  gradle/libs.versions.toml
Labels: type: dependency changes

#1636 chore: update federation jvm to 2.2.0
  gradle.properties
Labels: type: dependency changes

#1633 build: migrate to use buildSrc and convention plugins
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/com.expediagroup.graphql.conventions.gradle.kts
  clients/graphql-kotlin-client-jackson/build.gradle.kts
  clients/graphql-kotlin-client-serialization/build.gradle.kts
  clients/graphql-kotlin-client/build.gradle.kts
  clients/graphql-kotlin-ktor-client/build.gradle.kts
  clients/graphql-kotlin-spring-client/build.gradle.kts
  examples/build.gradle.kts
  examples/buildSrc/build.gradle.kts
  examples/buildSrc/settings.gradle.kts
  examples/buildSrc/src/main/kotlin/com.expediagroup.graphql.examples.conventions.gradle.kts
  examples/client/gradle-client/build.gradle.kts
  examples/client/maven-client/build.gradle.kts
  examples/client/server/build.gradle.kts
  examples/federation/products-subgraph/build.gradle.kts
  examples/federation/reviews-subgraph/build.gradle.kts
  examples/gradle.properties
  examples/server/ktor-server/build.gradle.kts
  examples/server/spring-server/build.gradle.kts
  examples/settings.gradle.kts
  executions/graphql-kotlin-automatic-persisted-queries/build.gradle.kts
  executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
  executions/graphql-kotlin-dataloader/build.gradle.kts
  generator/graphql-kotlin-federation/build.gradle.kts
  generator/graphql-kotlin-schema-generator/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  plugins/client/graphql-kotlin-client-generator/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-maven-plugin/build.gradle.kts
  plugins/schema/graphql-kotlin-federated-hooks-provider/build.gradle.kts
  plugins/schema/graphql-kotlin-hooks-provider/build.gradle.kts
  plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts
  servers/graphql-kotlin-server/build.gradle.kts
  servers/graphql-kotlin-spring-server/build.gradle.kts
  settings.gradle.kts
Labels: type: tool update

#1637 build: fed compatibility test action should fail if any test failed
  .github/workflows/federation-compatibility.yml
Labels: type: tool update

#1635 build: use typesafe project accessors
  clients/graphql-kotlin-client-jackson/build.gradle.kts
  clients/graphql-kotlin-client-serialization/build.gradle.kts
  clients/graphql-kotlin-ktor-client/build.gradle.kts
  clients/graphql-kotlin-spring-client/build.gradle.kts
  executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
  generator/graphql-kotlin-federation/build.gradle.kts
  gradle/libs.versions.toml
  plugins/client/graphql-kotlin-client-generator/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-maven-plugin/build.gradle.kts
  plugins/schema/graphql-kotlin-federated-hooks-provider/build.gradle.kts
  plugins/schema/graphql-kotlin-hooks-provider/build.gradle.kts
  plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts
  servers/graphql-kotlin-server/build.gradle.kts
  servers/graphql-kotlin-spring-server/build.gradle.kts
  settings.gradle.kts
Labels: type: tool update

#1641 feat: config property to print schema
  servers/graphql-kotlin-spring-server/build.gradle.kts
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/FederatedSchemaAutoConfiguration.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/NonFederatedSchemaAutoConfiguration.kt
  website/docs/server/spring-server/spring-properties.md
Labels: changes: minor, module: server

#1646 chore: update v6 docs with printSchema config
  website/versioned_docs/version-6.x.x/server/spring-server/spring-properties.md
Labels: type: documentation

#1647 fix: graphiql bundle version
  servers/graphql-kotlin-spring-server/src/main/resources/graphql-graphiql.html
Labels: changes: minor, module: server

#1652 feat: pass graphQLContext as fallback if deprecated context is null
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/dataFetchingEnvironmentExtensions.kt
Labels: changes: minor, module: server

#1653 fix: unit tests dataFetchingEnvironment DataLoader extension functions
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/dataFetchingEnvironmentExtensions.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/DataFetchingEnvironmentExtensionsKtTest.kt
Labels: changes: minor

#1638 update to SpringBoot 3 and Java 17
  .github/workflows/build-examples.yml
  .github/workflows/build-libraries.yml
  .github/workflows/federation-compatibility.yml
  .github/workflows/federation-composition.yml
  .github/workflows/plugin-it.yml
  .github/workflows/pr-check-federation.yml
  .github/workflows/release-code.yml
  buildSrc/src/main/kotlin/com.expediagroup.graphql.conventions.gradle.kts
  examples/buildSrc/src/main/kotlin/com.expediagroup.graphql.examples.conventions.gradle.kts
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/exceptions/ValidationException.kt
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/ValidatedQuery.kt
  examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/server/spring/subscriptions/SimpleSubscriptionIT.kt
  gradle.properties
  gradle/libs.versions.toml
  integration/federation-compatibility/build.gradle.kts
  integration/gradle-plugin-android-test/app/build.gradle.kts
  integration/gradle-plugin-android-test/app/src/main/AndroidManifest.xml
  integration/gradle-plugin-android-test/gradle/wrapper/gradle-wrapper.jar
  integration/gradle-plugin-android-test/gradle/wrapper/gradle-wrapper.properties
  integration/gradle-plugin-android-test/gradlew
  integration/gradle-plugin-android-test/gradlew.bat
  integration/gradle-plugin-integration-tests/build.gradle.kts
  integration/gradle-plugin-integration-tests/buildSrc/build.gradle.kts
  integration/gradle-plugin-integration-tests/buildSrc/src/main/kotlin/com.expediagroup.it-conventions.gradle.kts
  integration/gradle-plugin-integration-tests/buildSrc/src/main/kotlin/com/expediagroup/it/VerifyFileExistsTask.kt
  integration/gradle-plugin-integration-tests/client-generator/custom-scalars-jackson/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/custom-scalars-kotlinx/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/groovy-extension/build.gradle
  integration/gradle-plugin-integration-tests/client-generator/groovy-task/build.gradle
  integration/gradle-plugin-integration-tests/client-generator/jacoco/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/kotlin-extension/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/kotlin-task/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/ktor-jackson/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/ktor-kotlinx/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/multiple-tasks/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/polymorphic-types-jackson/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/polymorphic-types-kotlinx/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/skip-include/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/webclient-jackson/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/webclient-kotlinx/build.gradle.kts
  integration/gradle-plugin-integration-tests/download-sdl/groovy/build.gradle
  integration/gradle-plugin-integration-tests/download-sdl/kotlin/build.gradle.kts
  integration/gradle-plugin-integration-tests/introspection/groovy/build.gradle
  integration/gradle-plugin-integration-tests/introspection/kotlin/build.gradle.kts
  integration/gradle-plugin-integration-tests/sdl/classpath-hooks/build.gradle.kts
  integration/gradle-plugin-integration-tests/sdl/extension-groovy/build.gradle
  integration/gradle-plugin-integration-tests/sdl/extension-kotlin/build.gradle.kts
  integration/gradle-plugin-integration-tests/sdl/federated-hooks/build.gradle.kts
  integration/gradle-plugin-integration-tests/sdl/task-groovy/build.gradle
  integration/gradle-plugin-integration-tests/sdl/task-kotlin/build.gradle.kts
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLRequestParser.kt
  servers/graphql-kotlin-spring-server/src/main/resources/META-INF/spring.factories
  servers/graphql-kotlin-spring-server/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/SubscriptionRoutesConfigurationIT.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SubscriptionWebSocketHandlerIT.kt
Labels: changes: major
