Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2023-02, with the labels that each got.

#1668 chore: update to latest docusaurus version
  website/package-lock.json
  website/package.json
Labels: type: dependency changes

#1667 add ktor server plugin module
  examples/server/ktor-server/build.gradle.kts
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/CustomGraphQLContextFactory.kt
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/GraphQLModule.kt
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/KtorGraphQLRequestParser.kt
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/KtorServer.kt
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/ktorGraphQLSchema.kt
  examples/server/ktor-server/src/main/resources/graphql-playground.html
  gradle/libs.versions.toml
  servers/graphql-kotlin-ktor-server/build.gradle.kts
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQL.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLConfiguration.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLContextFactory.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParser.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLServer.kt
  servers/graphql-kotlin-ktor-server/src/main/resources/graphql-graphiql.html
  servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginConfigurationTest.kt
  servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt
  servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParserTest.kt
  servers/graphql-kotlin-ktor-server/src/test/resources/application.conf
  settings.gradle.kts
  website/docs/assets/ktor-initializer.png
  website/docs/server/ktor-server/ktor-configuration.md
  website/docs/server/ktor-server/ktor-graphql-context.md
  website/docs/server/ktor-server/ktor-http-request-response.md
  website/docs/server/ktor-server/ktor-overview.mdx
  website/docs/server/ktor-server/ktor-schema.md
  website/sidebars.js
Labels: type: enhancement, changes: minor

#1661 federation: add support for Apollo Federation subgraph spec v2.3
  examples/federation/compose-router.yaml
  examples/federation/compose-subgraphs.yaml
  examples/federation/docker-compose.yaml
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ComposeDirective.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ExternalDirective.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/InterfaceObjectDirective.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ShareableDirective.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/composeDirective/CustomSchema.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/intfObject/IntfObjectQuery.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/ComposeDirectiveIT.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/InterfaceObjectIT.kt
  integration/federation-compatibility/src/main/kotlin/com/expediagroup/federation/compatibility/CustomSchema.kt
  integration/federation-compatibility/src/main/kotlin/com/expediagroup/federation/compatibility/model/Inventory.kt
  integration/federation-compatibility/src/main/kotlin/com/expediagroup/federation/compatibility/model/Product.kt
  integration/gradle-plugin-integration-tests/src/integration/resources/sdl/custom.graphql
  integration/gradle-plugin-integration-tests/src/integration/resources/sdl/federated.graphql
  integration/maven-plugin-integration-tests/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
  integration/maven-plugin-integration-tests/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
  plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
  website/docs/schema-generator/federation/apollo-federation.mdx
  website/docs/schema-generator/federation/federated-directives.md
Labels: type: enhancement, changes: minor, module: generator

#1674 6.x.x feat: add support for federation v2.3
  examples/client/src/integration/wiremock/__files/schema.graphql
  examples/federation/gateway/.nvmrc
  examples/federation/gateway/index.js
  examples/federation/gateway/package-lock.json
  examples/federation/gateway/package.json
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ComposeDirective.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ExternalDirective.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/InterfaceObject.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ShareableDirective.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/composeDirective/CustomSchema.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/intfObject/IntfObjectQuery.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/ComposeDirectiveIT.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/InterfaceObjectIT.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/federatedTestConfig.kt
Labels: type: enhancement, changes: minor, module: generator

#1686 docs: update v6 docs with fed2.3 info
  website/versioned_docs/version-6.x.x/schema-generator/federation/apollo-federation.mdx
  website/versioned_docs/version-6.x.x/schema-generator/federation/federated-directives.md
Labels: type: documentation

#1684 fix(ktor-server): move plugin install to routing context
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQL.kt
Labels: changes: patch

#1687 fix federation integration workflows
  .github/workflows/continuous-integration.yml
  .github/workflows/federation-integration.yml
  .github/workflows/pr-check-federation.yml
  integration/federation-compatibility/docker-compose.yaml
Labels: type: tool update

#1688 [ktor plugin] refactor route configuration
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/GraphQLModule.kt
  servers/graphql-kotlin-ktor-server/build.gradle.kts
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQL.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLConfiguration.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLRoutes.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLContextFactory.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParser.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLServer.kt
  servers/graphql-kotlin-ktor-server/src/main/resources/graphql-graphiql.html
  servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt
  website/docs/server/ktor-server/ktor-configuration.md
  website/docs/server/ktor-server/ktor-http-request-response.md
  website/docs/server/ktor-server/ktor-overview.mdx
Labels: changes: major
