Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2023-09, with the labels that each got.

#1832 Keep response content type to application/json as default instead of application/graphql-response+json
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLRoutesConfiguration.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt
Labels: changes: patch

#1836 chore: update docusaurus to latest
  website/.nvmrc
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
Labels: type: documentation, type: dependency changes

#1835 chore: update dependencies to the latest
  .github/workflows/graalvm-integration.yml
  examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/exceptions/CustomDataFetcherExceptionHandler.kt
  gradle/libs.versions.toml
  integration/graalvm/common-graalvm-server/build.gradle.kts
  integration/graalvm/gradle.properties
  integration/graalvm/ktor-graalvm-server/build.gradle.kts
  integration/graalvm/maven-graalvm-server/build.gradle.kts
  integration/graalvm/spring-graalvm-server/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGraalVmMetadataTask.kt
Labels: changes: patch, type: dependency changes

#1842 fix: add explicit dependency between kapt and dokka
  servers/graphql-kotlin-spring-server/build.gradle.kts
Labels: type: tool update

#1848 chore: update docusaurus to point to v7 docs as latest
  website/docs/blogs-and-videos.md
  website/docusaurus.config.js
Labels: type: documentation
