Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2023-10, with the labels that each got.

#1871 chore: Update plugin goals in documentation
  website/docs/client/client-overview.mdx
  website/versioned_docs/version-3.x.x/client/client-overview.md
  website/versioned_docs/version-4.x.x/client/client-overview.mdx
  website/versioned_docs/version-5.x.x/client/client-overview.mdx
  website/versioned_docs/version-6.x.x/client/client-overview.mdx
Labels: type: documentation

#1875 chore: update to latest Gradle and Maven versions
  build.gradle.kts
  clients/graphql-kotlin-client-serialization/build.gradle.kts
  clients/graphql-kotlin-ktor-client/build.gradle.kts
  clients/graphql-kotlin-spring-client/build.gradle.kts
  examples/client/gradle-client/build.gradle.kts
  examples/client/maven-client/.mvn/wrapper/MavenWrapperDownloader.java
  examples/client/maven-client/.mvn/wrapper/maven-wrapper.jar
  examples/client/maven-client/.mvn/wrapper/maven-wrapper.properties
  examples/client/maven-client/mvnw
  examples/client/maven-client/mvnw.cmd
  examples/client/server/build.gradle.kts
  examples/federation/products-subgraph/build.gradle.kts
  examples/federation/reviews-subgraph/build.gradle.kts
  examples/server/ktor-server/build.gradle.kts
  examples/server/spring-server/build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  integration/federation-compatibility/build.gradle.kts
  integration/graalvm/build.gradle.kts
  integration/graalvm/common-graalvm-server/build.gradle.kts
  integration/graalvm/ktor-graalvm-server/build.gradle.kts
  integration/graalvm/maven-graalvm-server/.mvn/wrapper/maven-wrapper.jar
  integration/graalvm/maven-graalvm-server/.mvn/wrapper/maven-wrapper.properties
  integration/graalvm/maven-graalvm-server/build.gradle.kts
  integration/graalvm/maven-graalvm-server/mvnw
  integration/graalvm/maven-graalvm-server/mvnw.cmd
  integration/graalvm/maven-graalvm-server/pom.xml
  integration/graalvm/spring-graalvm-server/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/custom-scalars-jackson/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/custom-scalars-kotlinx/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/jacoco/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/kotlin-extension/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/kotlin-task/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/ktor-jackson/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/ktor-kotlinx/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/multiple-tasks/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/polymorphic-types-jackson/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/polymorphic-types-kotlinx/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/skip-include/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/webclient-jackson/build.gradle.kts
  integration/gradle-plugin-integration-tests/client-generator/webclient-kotlinx/build.gradle.kts
  integration/gradle-plugin-integration-tests/download-sdl/kotlin/build.gradle.kts
  integration/gradle-plugin-integration-tests/introspection/kotlin/build.gradle.kts
  integration/gradle-plugin-integration-tests/sdl/classpath-hooks/build.gradle.kts
  integration/gradle-plugin-integration-tests/sdl/extension-kotlin/build.gradle.kts
  integration/gradle-plugin-integration-tests/sdl/federated-hooks/build.gradle.kts
  integration/gradle-plugin-integration-tests/sdl/task-kotlin/build.gradle.kts
  integration/graphql-http-spec/ktor-server/build.gradle.kts
  integration/graphql-http-spec/spring-server/build.gradle.kts
  integration/maven-plugin-integration-tests/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/client-deprecated-type/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/download-sdl-timeout/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/integration/introspection-timeout/build.gradle.kts
  plugins/graphql-kotlin-maven-plugin/build.gradle.kts
  servers/graphql-kotlin-server/build.gradle.kts
  servers/graphql-kotlin-spring-server/build.gradle.kts
Labels: type: tool update

#1864 fix(federation): update federated hooks to support flow
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
Labels: changes: patch

#1861 fix(federation): skip fieldset validation when it includes type reference
  generator/graphql-kotlin-federation/build.gradle.kts
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateFieldSetSelection.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/key/success/_6/EntityReferencingParent.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/FederatedKeyDirectiveIT.kt
Labels: changes: patch
