Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2023-05, with the labels that each got.

#1764 docs: documentation for new GraalVm plugin tasks/goal
  clients/graphql-kotlin-client-jackson/README.md
  clients/graphql-kotlin-client-serialization/README.md
  clients/graphql-kotlin-client/README.md
  clients/graphql-kotlin-ktor-client/README.md
  clients/graphql-kotlin-spring-client/README.md
  executions/graphql-kotlin-automatic-persisted-queries/README.md
  executions/graphql-kotlin-dataloader-instrumentation/README.md
  executions/graphql-kotlin-dataloader/README.md
  generator/graphql-kotlin-federation/README.md
  generator/graphql-kotlin-schema-generator/README.md
  integration/graalvm/maven-graalvm-server/pom.xml
  plugins/client/graphql-kotlin-client-generator/README.md
  plugins/graphql-kotlin-gradle-plugin/README.md
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGraalVmMetadataTask.kt
  plugins/graphql-kotlin-maven-plugin/README.md
  plugins/schema/graphql-kotlin-federated-hooks-provider/README.md
  plugins/schema/graphql-kotlin-hooks-provider/README.md
  plugins/schema/graphql-kotlin-sdl-generator/README.md
  plugins/server/graphql-kotlin-graalvm-metadata-generator/README.md
  servers/graphql-kotlin-ktor-server/README.md
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLConfiguration.kt
  servers/graphql-kotlin-server/README.md
  servers/graphql-kotlin-spring-server/README.md
  website/docs/plugins/gradle-plugin-tasks.mdx
  website/docs/plugins/gradle-plugin-usage-client.mdx
  website/docs/plugins/gradle-plugin-usage-graalvm.mdx
  website/docs/plugins/gradle-plugin-usage-sdl.mdx
  website/docs/plugins/maven-plugin-goals.md
  website/docs/plugins/maven-plugin-usage-client.md
  website/docs/plugins/maven-plugin-usage-graalvm.md
  website/docs/plugins/maven-plugin-usage-sdl.md
  website/docs/server/ktor-server/ktor-configuration.md
  website/docs/server/ktor-server/ktor-graphql-context.md
  website/docs/server/ktor-server/ktor-schema.md
  website/package-lock.json
  website/package.json
  website/sidebars.js
Labels: type: documentation

#1769 feat: GraalVM native image support for Spring server
  .github/workflows/graalvm-integration.yml
  .github/workflows/pr-check.yml
  gradle/libs.versions.toml
  integration/graalvm/build.gradle.kts
  integration/graalvm/common-graalvm-server/src/main/kotlin/com/expediagroup/graalvm/schema/ContextualQuery.kt
  integration/graalvm/ktor-graalvm-server/src/main/kotlin/com/expediagroup/graalvm/ktor/Application.kt
  integration/graalvm/settings.gradle.kts
  integration/graalvm/spring-graalvm-server/build.gradle.kts
  integration/graalvm/spring-graalvm-server/src/main/kotlin/com/expediagroup/graalvm/spring/Application.kt
  integration/graalvm/spring-graalvm-server/src/main/kotlin/com/expediagroup/graalvm/spring/context/CustomContextFactory.kt
  integration/graalvm/spring-graalvm-server/src/main/resources/application.yaml
  integration/graalvm/spring-graalvm-server/src/test/kotlin/com/expediagroup/graalvm/spring/schema/TypesQueryTest.kt
  plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGraalVmMetadataTask.kt
  plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateGraalVmMetadataMojo.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/FederatedSchemaAutoConfiguration.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/NonFederatedSchemaAutoConfiguration.kt
  website/docs/plugins/gradle-plugin-tasks.mdx
  website/docs/plugins/gradle-plugin-usage-graalvm.mdx
  website/docs/plugins/maven-plugin-goals.md
  website/docs/plugins/maven-plugin-usage-graalvm.md
  website/docs/server/ktor-server/ktor-overview.mdx
  website/docs/server/spring-server/spring-beans.md
  website/docs/server/spring-server/spring-overview.mdx
Labels: changes: minor, module: server, module: plugin

#1766 docs: cleanup tasks/mojos usage documentation
  website/docs/plugins/gradle-plugin-usage-client.mdx
  website/docs/plugins/gradle-plugin-usage-sdl.mdx
  website/docs/plugins/maven-plugin-usage-client.md
  website/docs/plugins/maven-plugin-usage-sdl.md
Labels: type: documentation

#1778 fix(federation): relaxes `@requires` and `@external` constraints
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/ValidateFieldSelection.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateDirective.kt
  generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateFieldSetSelection.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/requires/success/_5/LeafRequires.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/requires/success/_6/RecursiveExternalRequires.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/requires/success/_7/ExternalRequiresType.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/FederatedRequiresDirectiveIT.kt
  website/docs/schema-generator/federation/federated-directives.md
Labels: type: bug, changes: patch, module: generator

#1780 chore: update dependencies to the latest
  gradle/libs.versions.toml
  integration/graalvm/maven-graalvm-server/.mvn/wrapper/maven-wrapper.properties
  integration/maven-plugin-integration-tests/.mvn/wrapper/maven-wrapper.properties
  plugins/server/graphql-kotlin-graalvm-metadata-generator/build.gradle.kts
Labels: changes: patch, type: dependency changes

#1783 feat: update graphql-java version with backwards compatible changes
  examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/server/spring/query/PolymorphicQueryIT.kt
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/PropertyDataFetcher.kt
  gradle.properties
Labels: changes: minor, type: dependency changes
