Repository ExpediaGroup/graphql-kotlin, pull requests merged in 2024-04, with the labels that each got.

#1950 chore: update to latest dependencies
  clients/graphql-kotlin-ktor-client/build.gradle.kts
  clients/graphql-kotlin-spring-client/build.gradle.kts
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/compose/ComposeDirectiveTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/contact/ContactDirectiveTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/link/LinkDirectiveTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/policy/PolicyDirectiveTest.kt
  generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/requiresscope/RequiresScopesDirectiveTest.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLSchemaExtensionsTest.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  integration/gradle-plugin-integration-tests/src/integration/resources/sdl/custom.graphql
  integration/gradle-plugin-integration-tests/src/integration/resources/sdl/federated.graphql
  integration/gradle-plugin-integration-tests/src/integration/resources/sdl/schema.graphql
  integration/maven-plugin-integration-tests/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
  integration/maven-plugin-integration-tests/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
  integration/maven-plugin-integration-tests/integration/generate-sdl/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
  integration/maven-plugin-integration-tests/integration/wiremock/__files/testSchema.graphql
  plugins/client/graphql-kotlin-client-generator/build.gradle.kts
  plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/IntrospectSchemaTest.kt
  plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
  plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
  plugins/schema/graphql-kotlin-sdl-generator/src/test/kotlin/com/expediagroup/graphql/plugin/schema/GenerateSDLTest.kt
  servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
  servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.kt
  servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt
Labels: type: dependency changes

#1936 fix: move exception handling into ktor statuspages
  examples/server/ktor-server/build.gradle.kts
  examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/GraphQLModule.kt
  gradle/libs.versions.toml
  servers/graphql-kotlin-ktor-server/build.gradle.kts
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQL.kt
  servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLStatusPages.kt
  servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt
  website/docs/server/ktor-server/ktor-http-request-response.md
  website/docs/server/ktor-server/ktor-overview.mdx
Labels: changes: major

#1959 Support built-in `ID` type serialization in `GraphQLServerRequest`
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/types/serializers/AnyNullableKSerializer.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/types/GraphQLServerRequestTest.kt
Labels: type: bug, changes: patch

#1958 Support built-in `ID` type serialization in `GraphQLServerRequest`
  servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/types/serializers/AnyNullableKSerializer.kt
  servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/types/GraphQLServerRequestTest.kt
Labels: type: bug, changes: patch

#1960 feat: ability to specify `@GraphQLName` on input types w/o suffix
  generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
  generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
  website/docs/schema-generator/customizing-schemas/renaming-fields.md
Labels: changes: minor
